import db from './db';

function generateId(): string {
  return Date.now().toString(36) + Math.random().toString(36).substring(2, 10);
}

db.exec('DELETE FROM achievements');
db.exec('DELETE FROM quizzes');
db.exec('DELETE FROM photos');
db.exec('DELETE FROM contributions');
db.exec('DELETE FROM itineraries');
db.exec('DELETE FROM users');
db.exec('DELETE FROM historical_events');
db.exec('DELETE FROM festivals');
db.exec('DELETE FROM foods');
db.exec('DELETE FROM monuments');
db.exec('DELETE FROM cities');
db.exec('DELETE FROM districts');
db.exec('DELETE FROM states');

const insertState = db.prepare('INSERT INTO states (id, name, capital, population, area, languages, formation_date, districts_count, major_cities, tourist_attractions, famous_foods, festivals, culture_description, economy_overview, image_url, statehood_day, website, latitude, longitude, slug) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)');
const insertMonument = db.prepare('INSERT INTO monuments (id, name, state_id, city_id, description, history, construction_details, architecture, visitor_info, latitude, longitude, image_url, image_urls, built_by, built_in, style, nearby_attractions, entry_fee, timings, best_time_to_visit, slug) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)');
const insertFood = db.prepare('INSERT INTO foods (id, name, state_id, category, description, history, ingredients, regional_variations, is_vegetarian, spice_level, image_url, slug) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)');
const insertFestival = db.prepare('INSERT INTO festivals (id, name, state_id, description, month, dates, traditions, is_national_holiday, type, image_url, slug) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)');
const insertEvent = db.prepare('INSERT INTO historical_events (id, title, description, date, year, period, category, personalities, locations, image_url) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)');

const INS: Record<string, string> = {};
for (const key of ['andhra', 'arunachal', 'assam', 'bihar', 'chhattisgarh', 'goa', 'gujarat', 'haryana', 'hp', 'jharkhand', 'karnataka', 'kerala', 'mp', 'maharashtra', 'manipur', 'meghalaya', 'mizoram', 'nagaland', 'odisha', 'punjab', 'rajasthan', 'sikkim', 'tn', 'telangana', 'tripura', 'up', 'uttarakhand', 'wb', 'delhi', 'chandigarh', 'puducherry', 'lakshadweep', 'andaman', 'daman', 'ladakh', 'jk']) {
  INS[key] = generateId();
}

insertState.run(INS.andhra, 'Andhra Pradesh', 'Amaravati', 54000000, 162968, JSON.stringify(['Telugu', 'English']), '2014-06-02', 26, JSON.stringify(['Visakhapatnam', 'Vijayawada', 'Guntur', 'Nellore', 'Kurnool']), JSON.stringify(['Tirupati Balaji Temple', 'Araku Valley', 'Borra Caves', 'Kondapalli Fort', 'RK Beach']), JSON.stringify(['Andhra Chicken Curry', 'Gongura Pachadi', 'Pesarattu', 'Pulihora', 'Gutti Vankaya']), JSON.stringify(['Makar Sankranti', 'Pongal', 'Ugadi', 'Dasara']), 'Andhra Pradesh is known for its rich cultural heritage, classical dance forms like Kuchipudi, and vibrant temple traditions. The state has a unique cuisine characterized by tangy and spicy flavors.', 'The economy is primarily agrarian with a strong presence in aquaculture and IT services. Visakhapatnam serves as a major port and industrial hub.', '/images/states/andhra-pradesh.jpg', '2014-06-02', 'https://www.andhrapradesh.gov.in', 15.9129, 79.7399, 'andhra-pradesh');
insertState.run(INS.arunachal, 'Arunachal Pradesh', 'Itanagar', 1700000, 83743, JSON.stringify(['Nyishi', 'Adi', 'Apatani', 'English']), '1987-02-20', 26, JSON.stringify(['Itanagar', 'Naharlagun', 'Pasighat', 'Tawang']), JSON.stringify(['Tawang Monastery', 'Bomdila Pass', 'Sela Pass', 'Ziro Valley', 'Namdapha National Park']), JSON.stringify(['Thukpa', 'Pike Pila', 'Momos', 'Apong', 'Pehak']), JSON.stringify(['Losar', 'Solung', 'Dree', 'Nyokum']), 'Arunachal Pradesh, the land of dawn-lit mountains, is home to diverse indigenous tribes with distinct languages and customs. Its vibrant festivals and Buddhist monasteries reflect a unique cultural mosaic.', 'The economy is driven by agriculture, horticulture, and tourism, with hydroelectric power as a growing sector.', '/images/states/arunachal-pradesh.jpg', '1987-02-20', 'https://www.arunachalpradesh.gov.in', 27.0844, 93.6053, 'arunachal-pradesh');
insertState.run(INS.assam, 'Assam', 'Dispur', 35000000, 78438, JSON.stringify(['Assamese', 'Bengali', 'Bodo', 'English']), '1950-01-26', 35, JSON.stringify(['Guwahati', 'Silchar', 'Dibrugarh', 'Jorhat', 'Nagaon']), JSON.stringify(['Kaziranga National Park', 'Manas National Park', 'Kamakhya Temple', 'Majuli Island', 'Sivasagar']), JSON.stringify(['Masor Tenga', 'Khar', 'Bamboo Shoot', 'Pitha', 'Aloo Pitika']), JSON.stringify(['Bihu', 'Durga Puja', 'Ambubachi Mela', 'Jonbil Mela']), 'Assam is known for its rich silk tradition, Satriya dance, and the one-horned rhinoceros. The state celebrates Bihu with great enthusiasm and is famous for its tea gardens.', 'The economy is based on tea cultivation, petroleum refining, and tourism. Assam produces over half of India\'s tea.', '/images/states/assam.jpg', '1950-01-26', 'https://www.assam.gov.in', 26.2006, 92.9376, 'assam');
insertState.run(INS.bihar, 'Bihar', 'Patna', 128000000, 94163, JSON.stringify(['Hindi', 'Bhojpuri', 'Maithili', 'English']), '1956-11-01', 38, JSON.stringify(['Patna', 'Gaya', 'Bhagalpur', 'Muzaffarpur', 'Bihar Sharif']), JSON.stringify(['Mahabodhi Temple', 'Nalanda University Ruins', 'Vikramshila University Ruins', 'Bodh Gaya', 'Rajgir']), JSON.stringify(['Litti Chokha', 'Sattu Paratha', 'Khaja', 'Thekua', 'Dal Pitha']), JSON.stringify(['Chhath Puja', 'Sama Chakeva', 'Makara Sankranti']), 'Bihar has a glorious past as the center of ancient Indian empires and learning, home to Nalanda and Vikramshila universities. The state is known for its folk songs, Madhubani painting, and the devout Chhath Puja.', 'Agriculture employs most of the workforce, with growing sectors in dairy, fisheries, and small-scale industries.', '/images/states/bihar.jpg', '1956-11-01', 'https://www.bihar.gov.in', 25.0961, 85.3131, 'bihar');
insertState.run(INS.chhattisgarh, 'Chhattisgarh', 'Raipur', 30000000, 135192, JSON.stringify(['Chhattisgarhi', 'Hindi', 'English']), '2000-11-01', 28, JSON.stringify(['Raipur', 'Bilaspur', 'Durg', 'Raigarh', 'Korba']), JSON.stringify(['Chitrakote Falls', 'Tirathgarh Falls', 'Bastar Palace', 'Kanger Valley National Park', 'Barnawapara Sanctuary']), JSON.stringify(['Chila', 'Faraa', 'Aamat', 'Muthia', 'Khurmi']), JSON.stringify(['Bastar Dussehra', 'Hareli', 'Pola', 'Madai']), 'Chhattisgarh is known for its tribal heritage, traditional dances like Pandavani and Raut Nacha, and ancient temples. The state has rich forest resources and vibrant craft traditions.', 'The economy is driven by mining, steel production, power generation, and agriculture. It is a major producer of coal and steel.', '/images/states/chhattisgarh.jpg', '2000-11-01', 'https://www.cgstate.gov.in', 21.2787, 81.8661, 'chhattisgarh');
insertState.run(INS.goa, 'Goa', 'Panaji', 1500000, 3702, JSON.stringify(['Konkani', 'Marathi', 'Hindi', 'English']), '1987-05-30', 2, JSON.stringify(['Panaji', 'Margao', 'Vasco da Gama', 'Mapusa', 'Ponda']), JSON.stringify(['Baga Beach', 'Calangute Beach', 'Basilica of Bom Jesus', 'Dudhsagar Falls', 'Fort Aguada', 'Anjuna Beach']), JSON.stringify(['Fish Curry Rice', 'Pork Vindaloo', 'Bebinca', 'Sorpotel', 'Sannas']), JSON.stringify(['Goa Carnival', 'Shigmo', 'Christmas', 'New Year']), 'Goa blends Indian and Portuguese influences in its architecture, cuisine, and festivals. The state is famous for its pristine beaches, vibrant nightlife, and hospitable people.', 'Tourism is the mainstay of Goa\'s economy, along with mining, fisheries, and pharmaceuticals.', '/images/states/goa.jpg', '1987-05-30', 'https://www.goa.gov.in', 15.2993, 74.124, 'goa');
insertState.run(INS.gujarat, 'Gujarat', 'Gandhinagar', 64000000, 196024, JSON.stringify(['Gujarati', 'Hindi', 'English']), '1960-05-01', 33, JSON.stringify(['Ahmedabad', 'Surat', 'Vadodara', 'Rajkot', 'Bhavnagar']), JSON.stringify(['Statue of Unity', 'Somnath Temple', 'Dwarkadhish Temple', 'Rann of Kutch', 'Gir National Park']), JSON.stringify(['Dhokla', 'Khandvi', 'Thepla', 'Undhiyu', 'Fafda-Jalebi']), JSON.stringify(['Navratri', 'Diwali', 'Uttarayan', 'Janmashtami']), 'Gujarat is known for its vibrant Garba dance, colorful festivals, and rich tradition of handicrafts. The state is deeply associated with Mahatma Gandhi and the freedom struggle.', 'Gujarat is a major industrial hub with strengths in chemicals, pharmaceuticals, textiles, and petrochemicals. It has one of the highest GDPs among Indian states.', '/images/states/gujarat.jpg', '1960-05-01', 'https://www.gujarat.gov.in', 23.2156, 72.6369, 'gujarat');
insertState.run(INS.haryana, 'Haryana', 'Chandigarh', 30000000, 44212, JSON.stringify(['Haryanvi', 'Hindi', 'English']), '1966-11-01', 22, JSON.stringify(['Chandigarh', 'Faridabad', 'Gurugram', 'Panipat', 'Ambala']), JSON.stringify(['Sultanpur Bird Sanctuary', 'Kurukshetra', 'Pinjore Gardens', 'Morni Hills']), JSON.stringify(['Kadhi Pakora', 'Bajra Khichdi', 'Hara Dhania Cholia', 'Malpua']), JSON.stringify(['Baisakhi', 'Gugga Navami', 'Teej']), 'Haryana has a distinct cultural identity with roots in Vedic traditions, folk music, and the martial sport of wrestling. The state is known for its vibrant Phulkari embroidery and rustic cuisine.', 'Haryana has a strong agricultural economy with a rapidly growing industrial and services sector around Gurugram and Faridabad.', '/images/states/haryana.jpg', '1966-11-01', 'https://www.haryana.gov.in', 29.0588, 76.0856, 'haryana');
insertState.run(INS.hp, 'Himachal Pradesh', 'Shimla', 7500000, 55673, JSON.stringify(['Hindi', 'Pahari', 'English']), '1971-01-25', 12, JSON.stringify(['Shimla', 'Manali', 'Dharamshala', 'Kullu', 'Mandi']), JSON.stringify(['Shimla Mall Road', 'Rohtang Pass', 'Manikaran Sahib', 'Dalai Lama Temple', 'Khajjiar']), JSON.stringify(['Dham', 'Siddu', 'Babru', 'Channa Madra', 'Khatta']), JSON.stringify(['Kullu Dussehra', 'Shimla Summer Festival', 'Mandi Shivaratri']), 'Himachal Pradesh is known for its breathtaking Himalayan landscapes, apple orchards, and ancient hill temples. The state has a rich tradition of Pahari miniature paintings and wood carving.', 'Tourism, horticulture, and hydroelectric power are the pillars of the state economy, with apples being a major cash crop.', '/images/states/himachal-pradesh.jpg', '1971-01-25', 'https://www.himachal.gov.in', 31.1048, 77.1734, 'himachal-pradesh');
insertState.run(INS.jharkhand, 'Jharkhand', 'Ranchi', 38000000, 79716, JSON.stringify(['Hindi', 'Santali', 'Mundari', 'English']), '2000-11-15', 24, JSON.stringify(['Ranchi', 'Jamshedpur', 'Dhanbad', 'Bokaro', 'Deoghar']), JSON.stringify(['Hundru Falls', 'Betla National Park', 'Baidyanath Temple', 'Parasnath Hill', 'Dimna Lake']), JSON.stringify(['Dhuska', 'Pittha', 'Handia', 'Malpua', 'Litti Chokha']), JSON.stringify(['Sarhul', 'Karma', 'Sohrai', 'Tusu']), 'Jharkhand is rich in tribal culture with vibrant festivals, folk dances, and music traditions. The state is known for its mineral wealth and indigenous art forms like Sohrai painting.', 'Jharkhand is a major mineral producer, contributing significantly to India\'s coal, iron ore, and mica output. Industry centers around Jamshedpur and Bokaro.', '/images/states/jharkhand.jpg', '2000-11-15', 'https://www.jharkhand.gov.in', 23.3441, 85.3096, 'jharkhand');
insertState.run(INS.karnataka, 'Karnataka', 'Bengaluru', 68000000, 191791, JSON.stringify(['Kannada', 'English']), '1956-11-01', 31, JSON.stringify(['Bengaluru', 'Mysuru', 'Hubli', 'Mangaluru', 'Belagavi']), JSON.stringify(['Mysore Palace', 'Hampi Ruins', 'Gol Gumbaz', 'Coorg', 'Gokarna', 'Jog Falls']), JSON.stringify(['Bisi Bele Bath', 'Masala Dosa', 'Mysore Pak', 'Ragi Mudde', 'Udupi Sambhar']), JSON.stringify(['Mysore Dasara', 'Ugadi', 'Makara Sankranthi', 'Kambala']), 'Karnataka has a rich cultural heritage spanning classical music, dance, and architecture from the Vijayanagara empire. The state is known for its diverse cuisine and literary tradition.', 'Karnataka is a leader in IT and biotechnology with Bengaluru as the Silicon Valley of India. Agriculture and manufacturing also contribute significantly.', '/images/states/karnataka.jpg', '1956-11-01', 'https://www.karnataka.gov.in', 12.9716, 77.5946, 'karnataka');
insertState.run(INS.kerala, 'Kerala', 'Thiruvananthapuram', 35000000, 38863, JSON.stringify(['Malayalam', 'English']), '1956-11-01', 14, JSON.stringify(['Thiruvananthapuram', 'Kochi', 'Kozhikode', 'Thrissur', 'Alappuzha']), JSON.stringify(['Munnar', 'Alleppey Backwaters', 'Kerala Backwaters', 'Wayanad', 'Kovalam', 'Thekkady', 'Cochin']), JSON.stringify(['Appam with Stew', 'Puttu and Kadala Curry', 'Malabar Biryani', 'Sadya', 'Banana Chips']), JSON.stringify(['Onam', 'Vishu', 'Thrissur Pooram', 'Christmas']), 'Kerala is known for its lush backwaters, classical dance forms like Kathakali, and high human development indices. The state has a unique blend of Dravidian and colonial influences.', 'The economy is driven by remittances from the diaspora, tourism, spices, and fisheries. Kerala has the highest literacy rate in India.', '/images/states/kerala.jpg', '1956-11-01', 'https://www.kerala.gov.in', 10.8505, 76.2711, 'kerala');
insertState.run(INS.mp, 'Madhya Pradesh', 'Bhopal', 85000000, 308252, JSON.stringify(['Hindi', 'English']), '1956-11-01', 52, JSON.stringify(['Bhopal', 'Indore', 'Gwalior', 'Jabalpur', 'Ujjain']), JSON.stringify(['Khajuraho Temples', 'Sanchi Stupa', 'Kanha National Park', 'Bandhavgarh National Park', 'Bhimbetka Caves']), JSON.stringify(['Poha Jalebi', 'Bhutte ka Kees', 'Dal Bafla', 'Mawa Bati', 'Sev Tamatar']), JSON.stringify(['Khajuraho Dance Festival', 'Bhagoria', 'Diwali']), 'Madhya Pradesh is the heart of India, known for its ancient temple heritage, wildlife sanctuaries, and tribal culture. The state has a rich tradition of classical music and folk arts.', 'Agriculture is the mainstay, with significant production of wheat, soybeans, and pulses. Tourism is growing around wildlife reserves and heritage sites.', '/images/states/madhya-pradesh.jpg', '1956-11-01', 'https://www.mp.gov.in', 23.2599, 77.4126, 'madhya-pradesh');
insertState.run(INS.maharashtra, 'Maharashtra', 'Mumbai', 124000000, 307713, JSON.stringify(['Marathi', 'Hindi', 'English']), '1960-05-01', 36, JSON.stringify(['Mumbai', 'Pune', 'Nagpur', 'Thane', 'Nashik']), JSON.stringify(['Gateway of India', 'Ajanta Caves', 'Ellora Caves', 'Elephanta Caves', 'Lonavala', 'Mahabaleshwar', 'Shirdi']), JSON.stringify(['Vada Pav', 'Pav Bhaji', 'Puran Poli', 'Modak', 'Bhelpuri']), JSON.stringify(['Ganesh Chaturthi', 'Gudi Padwa', 'Eid', 'Diwali']), 'Maharashtra is a melting pot of cultures, home to Bollywood, vibrant Ganesh Chaturthi celebrations, and a rich tradition of Marathi theatre and literature. The state has a unique blend of urban sophistication and rural traditions.', 'Maharashtra has the largest economy of any Indian state, driven by finance, IT, manufacturing, and entertainment in the Mumbai-Pune belt.', '/images/states/maharashtra.jpg', '1960-05-01', 'https://www.maharashtra.gov.in', 19.7515, 75.7139, 'maharashtra');
insertState.run(INS.manipur, 'Manipur', 'Imphal', 3300000, 22327, JSON.stringify(['Meitei', 'English']), '1972-01-21', 16, JSON.stringify(['Imphal', 'Bishnupur', 'Thoubal', 'Churachandpur']), JSON.stringify(['Loktak Lake', 'Kangla Fort', 'Shri Govindajee Temple', 'Ima Market', 'Keibul Lamjao National Park']), JSON.stringify(['Eromba', 'Singju', 'Ngari', 'Paaknam', 'Chamthong']), JSON.stringify(['Lai Haraoba', 'Yaoshang', 'Ningol Chakouba', 'Kang Chingba']), 'Manipur is known for its classical Ras Leela dance, polo origins, and scenic landscapes. The state has a distinct Meitei culture with rich traditions of martial arts and handloom.', 'The economy is primarily agricultural with growing sectors in handicrafts, tourism, and power generation.', '/images/states/manipur.jpg', '1972-01-21', 'https://www.manipur.gov.in', 24.6637, 93.9063, 'manipur');
insertState.run(INS.meghalaya, 'Meghalaya', 'Shillong', 3300000, 22429, JSON.stringify(['Khasi', 'Garo', 'English']), '1972-01-21', 12, JSON.stringify(['Shillong', 'Tura', 'Nongstoin', 'Jowai']), JSON.stringify(['Cherrapunji', 'Mawsynram', 'Dawki River', 'Umiam Lake', 'Seven Sisters Falls']), JSON.stringify(['Jadoh', 'Dohneiiong', 'Nakham Bitchi', 'Pumaloi', 'Minil Songa']), JSON.stringify(['Wangala', 'Nongkrem Dance', 'Shad Suk Mynsiem', 'Christmas']), 'Meghalaya, the abode of clouds, is known for its matrilineal Khasi and Garo tribes, living root bridges, and stunning waterfalls. The state has a unique blend of indigenous traditions and Christian influence.', 'Agriculture and tourism drive the economy, with coal and limestone mining as traditional industries.', '/images/states/meghalaya.jpg', '1972-01-21', 'https://www.meghalaya.gov.in', 25.467, 91.3662, 'meghalaya');
insertState.run(INS.mizoram, 'Mizoram', 'Aizawl', 1200000, 21081, JSON.stringify(['Mizo', 'English']), '1987-02-20', 11, JSON.stringify(['Aizawl', 'Lunglei', 'Champhai', 'Serchhip']), JSON.stringify(['Reiek Tlang', 'Vantawng Falls', 'Durtlang Hills', 'Mizoram State Museum', 'Phawngpui Peak']), JSON.stringify(['Misa Mach Poora', 'Bamboo Shoot Fry', 'Vawksa Rep', 'Chhum Han', 'Panch Phoron']), JSON.stringify(['Chapchar Kut', 'Mim Kut', 'Pawl Kut', 'Christmas']), 'Mizoram has a vibrant tribal culture with colorful festivals, handloom traditions, and a strong sense of community. The state has one of the highest literacy rates in India.', 'The economy is based on agriculture, forestry, and handloom, with tourism emerging as a promising sector.', '/images/states/mizoram.jpg', '1987-02-20', 'https://www.mizoram.gov.in', 23.1645, 92.9376, 'mizoram');
insertState.run(INS.nagaland, 'Nagaland', 'Kohima', 2000000, 16579, JSON.stringify(['Nagamese', 'English']), '1963-12-01', 16, JSON.stringify(['Kohima', 'Dimapur', 'Mokokchung', 'Tuensang']), JSON.stringify(['Dzuko Valley', 'Kohima War Cemetery', 'Nagaland State Museum', 'Intanki National Park']), JSON.stringify(['Smoked Pork', 'Bamboo Shoot', 'Naga King Chilli', 'Galho', 'Zutho']), JSON.stringify(['Hornbill Festival', 'Moatsu', 'Sekrenyi', 'Aoleang']), 'Nagaland is known for its diverse tribal communities, each with distinct languages, attire, and festivals. The Hornbill Festival showcases the state\'s rich cultural heritage.', 'Agriculture and forestry are the main economic activities, with tourism growing around the annual Hornbill Festival.', '/images/states/nagaland.jpg', '1963-12-01', 'https://www.nagaland.gov.in', 25.6751, 94.1086, 'nagaland');
insertState.run(INS.odisha, 'Odisha', 'Bhubaneswar', 46000000, 155707, JSON.stringify(['Odia', 'Hindi', 'English']), '1956-11-01', 30, JSON.stringify(['Bhubaneswar', 'Cuttack', 'Rourkela', 'Puri', 'Berhampur']), JSON.stringify(['Konark Sun Temple', 'Jagannath Temple', 'Chilika Lake', 'Lingaraj Temple', 'Puri Beach']), JSON.stringify(['Pakhala Bhata', 'Dalma', 'Chhena Poda', 'Rasabali', 'Macha Ghanta']), JSON.stringify(['Rath Yatra', 'Raja Parba', 'Durga Puja', 'Kali Puja']), 'Odisha is known for its magnificent temple architecture, classical Odissi dance, and rich tribal heritage. The state celebrates Rath Yatra with spectacular fervor.', 'The economy combines agriculture, mining, and a growing IT sector. Odisha is a leading producer of minerals like iron ore and bauxite.', '/images/states/odisha.jpg', '1956-11-01', 'https://www.odisha.gov.in', 20.9517, 85.0985, 'odisha');
insertState.run(INS.punjab, 'Punjab', 'Chandigarh', 30000000, 50362, JSON.stringify(['Punjabi', 'Hindi', 'English']), '1966-11-01', 23, JSON.stringify(['Chandigarh', 'Amritsar', 'Ludhiana', 'Jalandhar', 'Patiala']), JSON.stringify(['Golden Temple', 'Wagah Border', 'Jallianwala Bagh', 'Rock Garden', 'Anandpur Sahib']), JSON.stringify(['Butter Chicken', 'Sarson da Saag', 'Makki di Roti', 'Tandoori Chicken', 'Lassi']), JSON.stringify(['Baisakhi', 'Lohri', 'Gurpurab', 'Hola Mohalla']), 'Punjab is the land of five rivers, known for its vibrant Bhangra dance, Sikh heritage, and warm hospitality. The state has a rich tradition of Punjabi literature and martial arts.', 'Punjab is the breadbasket of India with a strong agricultural economy. Manufacturing and small-scale industries are growing rapidly.', '/images/states/punjab.jpg', '1966-11-01', 'https://www.punjab.gov.in', 30.9009, 75.8573, 'punjab');
insertState.run(INS.rajasthan, 'Rajasthan', 'Jaipur', 79000000, 342239, JSON.stringify(['Rajasthani', 'Hindi', 'English']), '1956-11-01', 33, JSON.stringify(['Jaipur', 'Jodhpur', 'Udaipur', 'Bikaner', 'Ajmer']), JSON.stringify(['Hawa Mahal', 'Amber Fort', 'City Palace Jaipur', 'Mehrangarh Fort', 'Lake Pichola', 'Thar Desert', 'Ranthambore National Park']), JSON.stringify(['Dal Baati Churma', 'Laal Maas', 'Gatte ki Sabzi', 'Ker Sangri', 'Mohan Thaal']), JSON.stringify(['Teej', 'Gangaur', 'Pushkar Camel Fair', 'Diwali']), 'Rajasthan is known for its majestic forts, vibrant textiles, and colorful festivals. The state has a rich Rajput heritage reflected in its music, dance, and architecture.', 'Tourism is the mainstay, along with agriculture, textiles, and mining. Rajasthan is a major producer of marble, sandstone, and wool.', '/images/states/rajasthan.jpg', '1956-11-01', 'https://www.rajasthan.gov.in', 27.0238, 74.2179, 'rajasthan');
insertState.run(INS.sikkim, 'Sikkim', 'Gangtok', 700000, 7096, JSON.stringify(['Nepali', 'Bhutia', 'Lepcha', 'English']), '1975-05-16', 6, JSON.stringify(['Gangtok', 'Namchi', 'Mangan', 'Geyzing']), JSON.stringify(['Nathu La Pass', 'Tsomgo Lake', 'Rumtek Monastery', 'Yuksom', 'Goecha La']), JSON.stringify(['Momos', 'Thukpa', 'Phagshapa', 'Gundruk', 'Sel Roti']), JSON.stringify(['Losar', 'Saga Dawa', 'Pang Lhabsol', 'Dasain']), 'Sikkim is a Himalayan paradise known for its pristine landscapes, Buddhist monasteries, and organic farming. The state is India\'s first fully organic state.', 'Tourism, hydropower, and organic agriculture form the economic backbone of Sikkim.', '/images/states/sikkim.jpg', '1975-05-16', 'https://www.sikkim.gov.in', 27.533, 88.5122, 'sikkim');
insertState.run(INS.tn, 'Tamil Nadu', 'Chennai', 78000000, 130058, JSON.stringify(['Tamil', 'English']), '1956-11-01', 38, JSON.stringify(['Chennai', 'Coimbatore', 'Madurai', 'Tiruchirappalli', 'Salem']), JSON.stringify(['Meenakshi Temple', 'Marina Beach', 'Ooty', 'Kodaikanal', 'Mahabalipuram', 'Rameswaram', 'Kanyakumari']), JSON.stringify(['Dosa', 'Idli', 'Sambhar', 'Chettinad Chicken', 'Pongal']), JSON.stringify(['Pongal', 'Tamil New Year', 'Deepavali', 'Karthigai Deepam']), 'Tamil Nadu is the heart of Dravidian culture, known for its magnificent temple architecture, classical Bharatanatyam dance, and ancient Tamil literature. The state has a vibrant film industry and rich culinary heritage.', 'Tamil Nadu has a diverse economy with strengths in automobile manufacturing, IT, textiles, and agriculture.', '/images/states/tamil-nadu.jpg', '1956-11-01', 'https://www.tn.gov.in', 11.1271, 78.6569, 'tamil-nadu');
insertState.run(INS.telangana, 'Telangana', 'Hyderabad', 39000000, 112077, JSON.stringify(['Telugu', 'Urdu', 'English']), '2014-06-02', 33, JSON.stringify(['Hyderabad', 'Warangal', 'Karimnagar', 'Nizamabad', 'Nalgonda']), JSON.stringify(['Charminar', 'Golconda Fort', 'Ramoji Film City', 'Hussain Sagar', 'Birla Mandir']), JSON.stringify(['Hyderabadi Biryani', 'Mirchi ka Salan', 'Double ka Meetha', 'Qubani ka Meetha', 'Haleem']), JSON.stringify(['Bathukamma', 'Bonalu', 'Makar Sankranti', 'Ugadi']), 'Telangana has a unique culture blending Telugu traditions with Nizami influences, evident in its architecture, cuisine, and arts. The state is known for its vibrant folk dances and pearl trade.', 'Hyderabad is a major IT and pharmaceutical hub. Agriculture remains important with the Godavari river basin supporting extensive farming.', '/images/states/telangana.jpg', '2014-06-02', 'https://www.telangana.gov.in', 18.1124, 79.0193, 'telangana');
insertState.run(INS.tripura, 'Tripura', 'Agartala', 4000000, 10486, JSON.stringify(['Bengali', 'Kokborok', 'English']), '1972-01-21', 8, JSON.stringify(['Agartala', 'Udaipur', 'Dharmanagar', 'Kailashahar']), JSON.stringify(['Ujjayanta Palace', 'Neermahal', 'Tripura Sundari Temple', 'Sepahijala Zoo']), JSON.stringify(['Mui Borok', 'Chanapuri', 'Wahan Mosdeng', 'Gudok', 'Bai']), JSON.stringify(['Kharchi Puja', 'Garia Puja', 'Durga Puja', 'Bihu']), 'Tripura is known for its royal heritage, indigenous tribal communities, and exquisite handloom textiles. The state has a rich tradition of folk music and dance.', 'Agriculture and forestry are the primary economic activities, with bamboo and rubber cultivation being significant.', '/images/states/tripura.jpg', '1972-01-21', 'https://www.tripura.gov.in', 23.9408, 91.9882, 'tripura');
insertState.run(INS.up, 'Uttar Pradesh', 'Lucknow', 241000000, 243290, JSON.stringify(['Hindi', 'Urdu', 'English']), '1950-01-26', 75, JSON.stringify(['Lucknow', 'Agra', 'Varanasi', 'Kanpur', 'Prayagraj']), JSON.stringify(['Taj Mahal', 'Agra Fort', 'Fatehpur Sikri', 'Kashi Vishwanath Temple', 'Sarnath', 'Ayodhya']), JSON.stringify(['Tunday Kababi', 'Petha', 'Biryani', 'Kachori Sabzi', 'Gulab Jamun']), JSON.stringify(['Diwali', 'Holi', 'Kumbh Mela', 'Eid']), 'Uttar Pradesh is the heartland of Indian civilization, home to the sacred cities of Varanasi, Ayodhya, and Prayagraj. The state has a rich tradition of Hindustani classical music, Kathak dance, and Mughal-influenced cuisine.', 'Uttar Pradesh has the largest population of any Indian state with an economy based on agriculture, manufacturing, and tourism.', '/images/states/uttar-pradesh.jpg', '1950-01-26', 'https://www.up.gov.in', 27.0238, 80.9097, 'uttar-pradesh');
insertState.run(INS.uttarakhand, 'Uttarakhand', 'Dehradun', 12000000, 53483, JSON.stringify(['Hindi', 'Garhwali', 'Kumaoni', 'English']), '2000-11-09', 13, JSON.stringify(['Dehradun', 'Haridwar', 'Rishikesh', 'Nainital', 'Mussoorie']), JSON.stringify(['Jim Corbett National Park', 'Kedarnath Temple', 'Badrinath Temple', 'Valley of Flowers', 'Nainital Lake']), JSON.stringify(['Aloo Ke Gutke', 'Kafuli', 'Chainsoo', 'Bhatt Ki Churkani', 'Singal']), JSON.stringify(['Kumbh Mela', 'Ganga Dussehra', 'Nanda Devi Raj Jaat']), 'Uttarakhand, the land of gods, is known for its Himalayan pilgrimage sites, yoga centers, and breathtaking natural beauty. The state has a distinct Garhwali and Kumaoni cultural heritage.', 'Tourism, pilgrimage, and hydropower are the primary economic drivers, along with horticulture and forestry.', '/images/states/uttarakhand.jpg', '2000-11-09', 'https://www.uk.gov.in', 30.0668, 79.0193, 'uttarakhand');
insertState.run(INS.wb, 'West Bengal', 'Kolkata', 98000000, 88752, JSON.stringify(['Bengali', 'Hindi', 'English']), '1956-11-01', 23, JSON.stringify(['Kolkata', 'Howrah', 'Durgapur', 'Asansol', 'Siliguri']), JSON.stringify(['Victoria Memorial', 'Howrah Bridge', 'Sundarbans National Park', 'Darjeeling', 'Kalighat Temple']), JSON.stringify(['Rasgulla', 'Macher Jhol', 'Kathi Roll', 'Mishti Doi', 'Shorshe Ilish']), JSON.stringify(['Durga Puja', 'Kali Puja', 'Poila Boishakh', 'Saraswati Puja']), 'West Bengal is known for its rich literary tradition, Bengali cinema, and the magnificent Durga Puja festival. The state is the cultural capital of India with a deep heritage in music, art, and philosophy.', 'The economy is driven by agriculture, manufacturing, and the services sector. Kolkata is a major commercial and cultural hub of eastern India.', '/images/states/west-bengal.jpg', '1956-11-01', 'https://www.wb.gov.in', 22.9868, 87.855, 'west-bengal');
insertState.run(INS.delhi, 'Delhi', 'Delhi', 21000000, 1484, JSON.stringify(['Hindi', 'Punjabi', 'Urdu', 'English']), '1956-11-01', 11, JSON.stringify(['New Delhi', 'Dwarka', 'Rohini', 'Saket', 'Lajpat Nagar']), JSON.stringify(['Red Fort', 'Qutub Minar', 'India Gate', 'Lotus Temple', 'Akshardham Temple']), JSON.stringify(['Chole Bhature', 'Butter Chicken', 'Paranthe Wali Gali', 'Kebabs', 'Jalebis']), JSON.stringify(['Diwali', 'Holi', 'Dussehra', 'Republic Day Parade']), 'Delhi, the national capital, is a city where ancient history meets modernity. It has been the seat of power for centuries, reflected in its magnificent forts, tombs, and monuments.', 'Delhi has a diverse economy driven by government services, IT, retail, and tourism. It is a major transportation and commercial hub.', '/images/states/delhi.jpg', '1956-11-01', 'https://www.delhi.gov.in', 28.7041, 77.1025, 'delhi');
insertState.run(INS.chandigarh, 'Chandigarh', 'Chandigarh', 1200000, 114, JSON.stringify(['Hindi', 'Punjabi', 'English']), '1966-11-01', 1, JSON.stringify(['Chandigarh']), JSON.stringify(['Rock Garden', 'Sukhna Lake', 'Capitol Complex', 'Rose Garden', 'Elante Mall']), JSON.stringify(['Butter Chicken', 'Chole Bhature', 'Dahi Bhalla', 'Amritsari Kulcha']), JSON.stringify(['Baisakhi', 'Lohri', 'Diwali']), 'Chandigarh is India\'s first planned city, designed by Le Corbusier. It serves as the capital of both Punjab and Haryana, known for its modernist architecture and high quality of life.', 'The economy is driven by government services, IT, and retail trade. Chandigarh is a major education and healthcare hub.', '/images/states/chandigarh.jpg', '1966-11-01', 'https://www.chandigarh.gov.in', 30.7333, 76.7794, 'chandigarh');
insertState.run(INS.puducherry, 'Puducherry', 'Puducherry', 1600000, 492, JSON.stringify(['Tamil', 'French', 'English']), '1962-08-16', 4, JSON.stringify(['Puducherry', 'Karaikal', 'Mahe', 'Yanam']), JSON.stringify(['Promenade Beach', 'Sri Aurobindo Ashram', 'Auroville', 'French Quarter']), JSON.stringify(['Seafood', 'Puttu', 'Dosa', 'French Baguette']), JSON.stringify(['Pongal', 'Masi Magam', 'French Festival']), 'Puducherry is a unique blend of Tamil and French culture, with colonial architecture lining tree-shaded boulevards. The city is known for its spiritual ashrams and serene beaches.', 'Tourism, education, and IT services drive the economy of this small but culturally rich territory.', '/images/states/puducherry.jpg', '1962-08-16', 'https://www.py.gov.in', 11.9416, 79.8083, 'puducherry');
insertState.run(INS.lakshadweep, 'Lakshadweep', 'Kavaratti', 700000, 32, JSON.stringify(['Malayalam', 'Jeseri', 'English']), '1956-11-01', 1, JSON.stringify(['Kavaratti', 'Minicoy', 'Agatti']), JSON.stringify(['Agatti Beach', 'Bangaram Atoll', 'Marine Museum', 'Minicoy Island']), JSON.stringify(['Tuna Curry', 'Kadalakka', 'Masala Dosa', 'Coconut Based Dishes']), JSON.stringify(['Eid', 'Bakrid', 'Independence Day']), 'Lakshadweep is an archipelago of pristine coral islands in the Arabian Sea, known for its turquoise waters and marine biodiversity. The islands have a distinct culture blending Islamic traditions with Malayali influences.', 'Tourism and fisheries are the primary economic activities, with the islands being a popular destination for water sports.', '/images/states/lakshadweep.jpg', '1956-11-01', 'https://www.lakshadweep.gov.in', 10.5667, 72.6417, 'lakshadweep');
insertState.run(INS.andaman, 'Andaman and Nicobar Islands', 'Port Blair', 400000, 8249, JSON.stringify(['Hindi', 'Bengali', 'Tamil', 'English']), '1956-11-01', 3, JSON.stringify(['Port Blair', 'Havelock Island', 'Neil Island']), JSON.stringify(['Cellular Jail', 'Radhanagar Beach', 'Baratang Island', 'Ross Island']), JSON.stringify(['Seafood', 'Grilled Fish', 'Prawn Curry', 'Coconut Rice']), JSON.stringify(['Island Tourism Festival', 'Diwali', 'Pongal']), 'The Andaman and Nicobar Islands are a tropical paradise with pristine beaches, coral reefs, and lush rainforests. The islands have a rich history from the British colonial era and indigenous tribal cultures.', 'Tourism is the main industry, along with fisheries, coconut plantations, and timber.', '/images/states/andaman-and-nicobar-islands.jpg', '1956-11-01', 'https://www.andaman.gov.in', 11.7401, 92.6586, 'andaman-and-nicobar-islands');
insertState.run(INS.daman, 'Daman and Diu', 'Daman', 600000, 112, JSON.stringify(['Gujarati', 'Konkani', 'Portuguese', 'English']), '1987-05-30', 2, JSON.stringify(['Daman', 'Diu']), JSON.stringify(['Diu Fort', 'Nagoa Beach', 'Chapel of Our Lady', 'Devka Beach']), JSON.stringify(['Pork Vindaloo', 'Seafood', 'Bebinca', 'Feni']), JSON.stringify(['Daman Festival', 'Christmas', 'Carnival']), 'Daman and Diu have a unique Portuguese-influenced culture reflected in their architecture, cuisine, and festivals. The territories are known for their serene beaches and colonial charm.', 'Tourism, fishing, and small-scale industries form the economic base of these coastal territories.', '/images/states/daman-and-diu.jpg', '1987-05-30', 'https://www.daman.gov.in', 20.4284, 72.8397, 'daman-and-diu');
insertState.run(INS.ladakh, 'Ladakh', 'Leh', 300000, 96701, JSON.stringify(['Ladakhi', 'Hindi', 'English']), '2019-10-31', 2, JSON.stringify(['Leh', 'Kargil', 'Nubra', 'Zanskar']), JSON.stringify(['Pangong Lake', 'Khardung La Pass', 'Nubra Valley', 'Magnetic Hill', 'Shanti Stupa']), JSON.stringify(['Thukpa', 'Momos', 'Skyu', 'Chhurpi', 'Butter Tea']), JSON.stringify(['Hemis Festival', 'Losar', 'Dosmoche']), 'Ladakh is known for its stark Himalayan landscapes, Tibetan Buddhist monasteries, and vibrant festival traditions. The region is often called Little Tibet for its cultural affinity.', 'Tourism, agriculture, and handicrafts are the main economic activities, with trekking and adventure tourism growing rapidly.', '/images/states/ladakh.jpg', '2019-10-31', 'https://www.ladakh.gov.in', 34.1526, 77.577, 'ladakh');
insertState.run(INS.jk, 'Jammu and Kashmir', 'Srinagar', 14000000, 222236, JSON.stringify(['Kashmiri', 'Dogri', 'Urdu', 'Hindi', 'English']), '2019-10-31', 20, JSON.stringify(['Srinagar', 'Jammu', 'Anantnag', 'Baramulla', 'Kathua']), JSON.stringify(['Dal Lake', 'Gulmarg', 'Pahalgam', 'Sonamarg', 'Vaishno Devi']), JSON.stringify(['Rogan Josh', 'Wazwan', 'Yakhni', 'Gushtaba', 'Kahwa']), JSON.stringify(['Eid', 'Navroz', 'Lohri', 'Shivaratri']), 'Jammu and Kashmir is renowned for its breathtaking Himalayan scenery, Mughal gardens, and rich tradition of Kashmiri handicrafts. The region has a unique syncretic culture blending Hindu, Muslim, and Buddhist influences.', 'Tourism, agriculture, horticulture, and handicrafts are the mainstays of the economy, with saffron and apples being key products.', '/images/states/jammu-and-kashmir.jpg', '2019-10-31', 'https://www.jk.gov.in', 33.7782, 76.5762, 'jammu-and-kashmir');

const MONUMENTS_DATA = [
  { n: 'Taj Mahal', sid: INS.up, cid: '', d: 'The Taj Mahal is an exquisite white marble mausoleum built by Emperor Shah Jahan in memory of his beloved wife Mumtaz Mahal. It is considered the finest example of Mughal architecture and a symbol of eternal love.', h: 'Construction began in 1631 and was completed in 1653, employing over 20,000 artisans from across the Mughal Empire. It was designated a UNESCO World Heritage Site in 1983.', cd: 'Built entirely of white marble inlaid with precious and semi-precious stones. The complex covers 42 acres with gardens, mosque, and guest house.', a: 'Mughal architecture combining Persian, Islamic, and Indian styles with symmetrical layouts, onion dome, and intricate pietra dura inlay work.', vi: 'Open from sunrise to sunset, closed on Fridays. Night viewing available on full moon nights.', lat: 27.1751, lng: 78.0421, iu: '/images/monuments/taj-mahal.jpg', ius: '["/images/monuments/taj-mahal.jpg"]', bb: 'Shah Jahan', bi: '1653', sty: 'Mughal', na: '["Agra Fort","Fatehpur Sikri","Mehtab Bagh","Akbar\'s Tomb"]', ef: '₹50 for Indians, ₹1100 for foreigners', ti: 'Sunrise to Sunset (6:00 AM - 6:30 PM), Closed on Friday', bt: 'October to March', sl: 'taj-mahal' },
  { n: 'Red Fort', sid: INS.delhi, cid: '', d: 'The Red Fort is a historic Mughal fort in Delhi that served as the main residence of Mughal emperors for nearly 200 years. Its massive red sandstone walls enclose a complex of palaces and gardens.', h: 'Built by Emperor Shah Jahan when he moved his capital from Agra to Delhi in 1639-1648. The fort was the site of the British trial of Bahadur Shah Zafar and where Nehru delivered his Tryst with Destiny speech.', cd: 'Built using red sandstone with intricate marble carvings. The fort spans 255 acres with walls rising up to 33 meters.', a: 'Mughal architecture with Persian influences, featuring Diwan-i-Aam, Diwan-i-Khas, Rang Mahal, and the famous Lahori Gate.', vi: 'Open Tuesday to Sunday, closed on Monday. Light and sound show in the evening.', lat: 28.6562, lng: 77.241, iu: '/images/monuments/red-fort.jpg', ius: '["/images/monuments/red-fort.jpg"]', bb: 'Shah Jahan', bi: '1648', sty: 'Mughal', na: '["Chandni Chowk","Jama Masjid","Raj Ghat","India Gate"]', ef: '₹35 for Indians, ₹550 for foreigners', ti: '9:30 AM - 4:30 PM, Closed on Monday', bt: 'October to March', sl: 'red-fort' },
  { n: 'Qutub Minar', sid: INS.delhi, cid: '', d: 'Qutub Minar is a towering 73-meter high minaret built of red sandstone and marble, making it the tallest brick minaret in the world. It is a masterpiece of Indo-Islamic architecture.', h: 'Construction was started by Qutb-ud-din Aibak in 1192 and completed by his successor Iltutmish. The complex also houses the Iron Pillar dating back to the 4th century.', cd: 'Five distinct storeys, each with a projecting balcony, tapering from 15 meters at base to 2.5 meters at top.', a: 'Indo-Islamic and Afghan architecture with intricate geometric patterns and Quranic inscriptions.', vi: 'Open all days from sunrise to sunset. Best visited in the morning or late afternoon.', lat: 28.5244, lng: 77.1855, iu: '/images/monuments/qutub-minar.jpg', ius: '["/images/monuments/qutub-minar.jpg"]', bb: 'Qutb-ud-din Aibak', bi: '1220', sty: 'Indo-Islamic', na: '["Lotus Temple","India Gate","Humayun\'s Tomb","Mehrauli Archaeological Park"]', ef: '₹30 for Indians, ₹500 for foreigners', ti: '7:00 AM - 5:00 PM', bt: 'October to March', sl: 'qutub-minar' },
  { n: 'Gateway of India', sid: INS.maharashtra, cid: '', d: 'The Gateway of India is a magnificent arch monument built on the waterfront in Mumbai. It was constructed to commemorate the visit of King George V and Queen Mary to India.', h: 'Built between 1911 and 1924, the monument served as the ceremonial entrance to India for British viceroys. It witnessed the departure of the last British troops in 1948.', cd: 'Built in yellow basalt and concrete, the arch stands 26 meters high with four turrets and intricate latticework.', a: 'Indo-Saracenic style combining Hindu and Muslim architectural elements with Gujarati influences.', vi: 'Open 24 hours. Best visited early morning or evening. Boat rides available from the jetty.', lat: 18.922, lng: 72.8347, iu: '/images/monuments/gateway-of-india.jpg', ius: '["/images/monuments/gateway-of-india.jpg"]', bb: 'George Wittet (architect)', bi: '1924', sty: 'Indo-Saracenic', na: '["Taj Mahal Hotel","Elephanta Caves","Marine Drive","Colaba Causeway"]', ef: 'Free', ti: 'Open 24 hours', bt: 'November to February', sl: 'gateway-of-india' },
  { n: 'India Gate', sid: INS.delhi, cid: '', d: 'India Gate is a war memorial located on the eastern edge of Rajpath in Delhi, commemorating Indian soldiers who died in World War I and the Afghan Wars.', h: 'Designed by Edwin Lutyens and completed in 1931, it originally bore the names of 13,516 British and Indian soldiers.', cd: 'Built in red sandstone and granite, the arch rises 42 meters with a shallow domed bowl at the top.', a: 'Triumphal arch style inspired by the Arc de Triomphe in Paris.', vi: 'Open 24 hours. Best visited at night when the monument is beautifully lit.', lat: 28.6129, lng: 77.2295, iu: '/images/monuments/india-gate.jpg', ius: '["/images/monuments/india-gate.jpg"]', bb: 'Edwin Lutyens', bi: '1931', sty: 'Triumphal Arch', na: '["Rashtrapati Bhavan","Rajpath","National War Memorial","Connaught Place"]', ef: 'Free', ti: 'Open 24 hours', bt: 'October to March', sl: 'india-gate' },
  { n: 'Hawa Mahal', sid: INS.rajasthan, cid: '', d: 'Hawa Mahal, or the Palace of Winds, is a stunning five-story palace built of pink sandstone with 953 small windows called jharokhas.', h: 'Built in 1799 by Maharaja Sawai Pratap Singh, the palace is an extension of the City Palace.', cd: 'The five-story pyramidal structure is adorned with intricate latticework and has no foundation.', a: 'Rajput architecture with a blend of Mughal styles, featuring the unique jharokha window design.', vi: 'Open all days. Best visited in the morning when the sunlight illuminates the palace.', lat: 26.9239, lng: 75.8267, iu: '/images/monuments/hawa-mahal.jpg', ius: '["/images/monuments/hawa-mahal.jpg"]', bb: 'Maharaja Sawai Pratap Singh', bi: '1799', sty: 'Rajput', na: '["City Palace Jaipur","Jantar Mantar","Amber Fort","Jaipur Bazaar"]', ef: '₹50 for Indians, ₹200 for foreigners', ti: '9:00 AM - 4:30 PM', bt: 'October to March', sl: 'hawa-mahal' },
  { n: 'Amber Fort', sid: INS.rajasthan, cid: '', d: 'Amber Fort is a magnificent hilltop fortress built in red sandstone and marble overlooking Maota Lake.', h: 'Built by Raja Man Singh I in 1592 and expanded by successive rulers.', cd: 'The fort complex includes the Diwan-i-Aam, Sheesh Mahal (Mirror Palace), and Sukh Niwas.', a: 'Rajput and Mughal architecture with intricate mirror work, carved marble panels, and elaborate frescoes.', vi: 'Open all days. Light and sound show in the evening.', lat: 26.9852, lng: 75.8516, iu: '/images/monuments/amber-fort.jpg', ius: '["/images/monuments/amber-fort.jpg"]', bb: 'Raja Man Singh I', bi: '1592', sty: 'Rajput-Mughal', na: '["Jaigarh Fort","Jal Mahal","Hawa Mahal","City Palace Jaipur"]', ef: '₹100 for Indians, ₹500 for foreigners', ti: '8:00 AM - 5:30 PM', bt: 'October to March', sl: 'amber-fort' },
  { n: 'Meenakshi Temple', sid: INS.tn, cid: '', d: 'Meenakshi Amman Temple is a historic Hindu temple in Madurai dedicated to Goddess Meenakshi and Lord Sundareswarar.', h: 'The temple was built in the 6th century with major expansions by the Nayak rulers in the 16th-17th centuries.', cd: 'The temple complex covers 14 acres with 14 gopurams, the tallest being the south tower at 51.9 meters.', a: 'Dravidian architecture with brightly painted gopurams, thousand-pillar hall, and sacred tank.', vi: 'Open daily from early morning to late night.', lat: 9.9195, lng: 78.1198, iu: '/images/monuments/meenakshi-temple.jpg', ius: '["/images/monuments/meenakshi-temple.jpg"]', bb: 'Kulashekara Pandya and Nayak rulers', bi: '6th century CE', sty: 'Dravidian', na: '["Thirumalai Nayakkar Palace","Koodal Alagar Temple","Gandhi Museum","Vaigai Dam"]', ef: 'Free (camera fee applicable)', ti: '5:00 AM - 12:30 PM, 4:00 PM - 10:00 PM', bt: 'October to March', sl: 'meenakshi-temple' },
  { n: 'Konark Sun Temple', sid: INS.odisha, cid: '', d: 'The Konark Sun Temple is a 13th-century solar temple designed as a colossal chariot for the Sun God Surya.', h: 'Built by King Narasimhadeva I of the Eastern Ganga dynasty in 1250 CE.', cd: 'The temple is built from khondalite rocks and measures 229 feet in height.', a: 'Kalinga architecture with intricate carvings depicting scenes from daily life and mythology.', vi: 'Open daily from sunrise to sunset.', lat: 19.8876, lng: 86.0945, iu: '/images/monuments/konark-sun-temple.jpg', ius: '["/images/monuments/konark-sun-temple.jpg"]', bb: 'King Narasimhadeva I', bi: '1250', sty: 'Kalinga', na: '["Chandrabhaga Beach","Konark Museum","Puri Jagannath Temple","Chilika Lake"]', ef: '₹40 for Indians, ₹600 for foreigners', ti: '6:00 AM - 8:00 PM', bt: 'October to March', sl: 'konark-sun-temple' },
  { n: 'Sanchi Stupa', sid: INS.mp, cid: '', d: 'The Great Stupa at Sanchi is one of the oldest stone structures in India, built by Emperor Ashoka in the 3rd century BCE.', h: 'Commissioned by Emperor Ashoka of the Maurya dynasty, later enlarged during the Shunga period.', cd: 'The hemispherical dome is 36.6 meters in diameter and 16.5 meters high.', a: 'Buddhist stupa architecture with distinctive torana gateways.', vi: 'Open daily from sunrise to sunset.', lat: 23.4793, lng: 77.7394, iu: '/images/monuments/sanchi-stupa.jpg', ius: '["/images/monuments/sanchi-stupa.jpg"]', bb: 'Emperor Ashoka', bi: '3rd century BCE', sty: 'Buddhist Mauryan', na: '["Udayagiri Caves","Vidisha","Bhojpur Temple","Bhimbetka Caves"]', ef: '₹40 for Indians, ₹600 for foreigners', ti: '6:00 AM - 6:00 PM', bt: 'October to March', sl: 'sanchi-stupa' },
  { n: 'Ajanta Caves', sid: INS.maharashtra, cid: '', d: 'The Ajanta Caves are a set of 29 Buddhist cave temples and monasteries carved into a horseshoe-shaped cliff.', h: 'Built in two phases from 2nd century BCE to 6th century CE, rediscovered by British officers in 1819.', cd: 'Each cave was meticulously carved from solid rock, featuring chaityas and viharas.', a: 'Rock-cut architecture with murals depicting Jataka tales and Buddha\'s life.', vi: 'Open Tuesday to Sunday, closed on Monday.', lat: 20.5285, lng: 75.748, iu: '/images/monuments/ajanta-caves.jpg', ius: '["/images/monuments/ajanta-caves.jpg"]', bb: 'Buddhist monks and Satavahana/Vakataka rulers', bi: '2nd century BCE', sty: 'Buddhist Rock-cut', na: '["Ellora Caves","Daulatabad Fort","Grishneshwar Temple","Aurangabad"]', ef: '₹40 for Indians, ₹600 for foreigners', ti: '9:00 AM - 5:30 PM, Closed on Monday', bt: 'October to March', sl: 'ajanta-caves' },
  { n: 'Ellora Caves', sid: INS.maharashtra, cid: '', d: 'Ellora Caves are a remarkable complex of 34 rock-cut monasteries and temples representing Buddhism, Hinduism, and Jainism.', h: 'Built between the 6th and 10th centuries by the Rashtrakuta dynasty.', cd: 'The Kailasa Temple was carved from a single rock, removing 200,000 tons of rock.', a: 'Rock-cut architecture with Dravidian, Buddhist, and Jain stylistic elements.', vi: 'Open Wednesday to Monday, closed on Tuesday.', lat: 20.0232, lng: 75.1778, iu: '/images/monuments/ellora-caves.jpg', ius: '["/images/monuments/ellora-caves.jpg"]', bb: 'Rashtrakuta and other dynasties', bi: '6th - 10th century CE', sty: 'Rock-cut (Hindu/Buddhist/Jain)', na: '["Ajanta Caves","Daulatabad Fort","Grishneshwar Temple","Aurangabad"]', ef: '₹40 for Indians, ₹600 for foreigners', ti: '8:00 AM - 5:30 PM, Closed on Tuesday', bt: 'October to March', sl: 'ellora-caves' },
  { n: 'Mahabodhi Temple', sid: INS.bihar, cid: '', d: 'The Mahabodhi Temple marks the spot where Lord Buddha attained enlightenment under the Bodhi tree.', h: 'The original temple was built by Emperor Ashoka in the 3rd century BCE.', cd: 'The temple rises to 55 meters with a pyramidal shikhara.', a: 'Buddhist temple architecture with a pyramidal spire in Gupta period style.', vi: 'Open daily from early morning to evening.', lat: 24.6959, lng: 84.9911, iu: '/images/monuments/mahabodhi-temple.jpg', ius: '["/images/monuments/mahabodhi-temple.jpg"]', bb: 'Emperor Ashoka (original)', bi: '3rd century BCE', sty: 'Gupta Buddhist', na: '["Bodh Gaya","Nalanda University Ruins","Rajgir","Vishwa Shanti Stupa"]', ef: 'Free', ti: '5:00 AM - 9:00 PM', bt: 'November to February', sl: 'mahabodhi-temple' },
  { n: 'Golden Temple', sid: INS.punjab, cid: '', d: 'Sri Harmandir Sahib, the Golden Temple, is the holiest shrine in Sikhism with a gold-plated sanctum.', h: 'Founded by Guru Arjan Dev in 1588 and completed in 1604.', cd: 'The sanctum is covered in 750 kg of pure gold.', a: 'Sikh architecture blending Hindu and Islamic styles with a distinctive gold dome.', vi: 'Open 24 hours daily. Free langar served round the clock.', lat: 31.6199, lng: 74.8765, iu: '/images/monuments/golden-temple.jpg', ius: '["/images/monuments/golden-temple.jpg"]', bb: 'Guru Arjan Dev and Maharaja Ranjit Singh', bi: '1604', sty: 'Sikh', na: '["Jallianwala Bagh","Wagah Border","Partition Museum","Ram Bagh"]', ef: 'Free', ti: 'Open 24 hours', bt: 'November to March', sl: 'golden-temple' },
  { n: 'Charminar', sid: INS.telangana, cid: '', d: 'Charminar is a majestic monument and mosque built in the heart of Hyderabad with four grand arches and four minarets.', h: 'Built by Muhammad Quli Qutb Shah in 1591 to commemorate the founding of Hyderabad.', cd: 'The structure is 56 meters high with four minarets each rising 48.7 meters.', a: 'Islamic Qutb Shahi architecture with Persian influences.', vi: 'Open all days. Best visited in the evening.', lat: 17.3616, lng: 78.4747, iu: '/images/monuments/charminar.jpg', ius: '["/images/monuments/charminar.jpg"]', bb: 'Muhammad Quli Qutb Shah', bi: '1591', sty: 'Islamic Qutb Shahi', na: '["Golconda Fort","Hussain Sagar","Salar Jung Museum","Mecca Masjid"]', ef: '₹25 for Indians, ₹300 for foreigners', ti: '9:00 AM - 5:30 PM', bt: 'October to March', sl: 'charminar' },
  { n: 'Mysore Palace', sid: INS.karnataka, cid: '', d: 'Mysore Palace is a magnificent royal residence and one of the most visited monuments in India.', h: 'Rebuilt in 1912 after a fire, designed by British architect Henry Irwin.', cd: 'Built in fine granite and pink marble, spanning three storeys.', a: 'Indo-Saracenic blending Hindu, Mughal, Rajput, and Gothic styles.', vi: 'Open daily. Spectacularly lit on Sundays and during Dasara.', lat: 12.3052, lng: 76.6552, iu: '/images/monuments/mysore-palace.jpg', ius: '["/images/monuments/mysore-palace.jpg"]', bb: 'Henry Irwin (architect)', bi: '1912', sty: 'Indo-Saracenic', na: '["Chamundi Hills","Brindavan Gardens","Mysore Zoo","St. Philomena\'s Church"]', ef: '₹70 for Indians, ₹400 for foreigners', ti: '10:00 AM - 5:30 PM', bt: 'October to March', sl: 'mysore-palace' },
  { n: 'Victoria Memorial', sid: INS.wb, cid: '', d: 'Victoria Memorial is a magnificent marble building in Kolkata dedicated to Queen Victoria.', h: 'Conceived by Lord Curzon and built between 1906 and 1921.', cd: 'Built in white Makrana marble, rising to 56 meters.', a: 'Indo-Saracenic with elements of Mughal, Venetian, Egyptian, and Deccani styles.', vi: 'Open Tuesday to Sunday, closed on Monday.', lat: 22.5465, lng: 88.3424, iu: '/images/monuments/victoria-memorial.jpg', ius: '["/images/monuments/victoria-memorial.jpg"]', bb: 'Lord Curzon', bi: '1921', sty: 'Indo-Saracenic', na: '["Howrah Bridge","Kalighat Temple","St. Paul\'s Cathedral","Maidan"]', ef: '₹30 for Indians, ₹500 for foreigners', ti: '10:00 AM - 5:00 PM, Closed on Monday', bt: 'November to February', sl: 'victoria-memorial' },
  { n: 'Hampi Ruins', sid: INS.karnataka, cid: '', d: 'The Hampi ruins are the remains of the Vijayanagara Empire, spread over 26 square kilometers.', h: 'Hampi was the capital of the Vijayanagara Empire from 1336 to 1565.', cd: 'Includes Virupaksha Temple, Vittala Temple with stone chariot, Lotus Mahal.', a: 'Vijayanagara architecture with Dravidian influences.', vi: 'Open daily from sunrise to sunset.', lat: 15.335, lng: 76.4601, iu: '/images/monuments/hampi-ruins.jpg', ius: '["/images/monuments/hampi-ruins.jpg"]', bb: 'Vijayanagara Empire rulers', bi: '14th - 16th century', sty: 'Vijayanagara Dravidian', na: '["Virupaksha Temple","Hippie Island","Tungabhadra Dam","Anegundi"]', ef: '₹40 for Indians, ₹600 for foreigners', ti: '6:00 AM - 6:30 PM', bt: 'October to March', sl: 'hampi-ruins' },
  { n: 'Elephanta Caves', sid: INS.maharashtra, cid: '', d: 'Elephanta Caves are rock-cut cave temples on Elephanta Island in Mumbai harbor, dedicated to Lord Shiva.', h: 'Built between the 5th and 7th centuries CE by the Kalachuri and Rashtrakuta rulers.', cd: 'The main cave measures 39 meters square with a 6-meter high trimurti of Lord Shiva.', a: 'Rock-cut Hindu temple architecture with massive monolithic sculptures.', vi: 'Accessible by ferry from Gateway of India. Open Tuesday to Sunday.', lat: 18.9633, lng: 72.93, iu: '/images/monuments/elephanta-caves.jpg', ius: '["/images/monuments/elephanta-caves.jpg"]', bb: 'Kalachuri and Rashtrakuta rulers', bi: '5th - 7th century CE', sty: 'Rock-cut Hindu', na: '["Gateway of India","Marine Drive","Colaba","Chhatrapati Shivaji Terminus"]', ef: '₹40 for Indians, ₹600 for foreigners', ti: '9:00 AM - 5:30 PM, Closed on Monday', bt: 'November to February', sl: 'elephanta-caves' },
  { n: 'Fatehpur Sikri', sid: INS.up, cid: '', d: 'Fatehpur Sikri is a magnificent fortified city built by Emperor Akbar as the Mughal capital.', h: 'Built between 1571 and 1585, abandoned shortly after due to water scarcity.', cd: 'Includes the Buland Darwaza, Panch Mahal, Diwan-i-Khas, and Jama Masjid.', a: 'Mughal architecture with distinct Hindu and Persian elements.', vi: 'Open daily. Best visited in the morning.', lat: 27.0956, lng: 77.6603, iu: '/images/monuments/fatehpur-sikri.jpg', ius: '["/images/monuments/fatehpur-sikri.jpg"]', bb: 'Emperor Akbar', bi: '1585', sty: 'Mughal', na: '["Taj Mahal","Agra Fort","Keoladeo National Park","Mathura"]', ef: '₹50 for Indians, ₹610 for foreigners', ti: '6:00 AM - 6:00 PM', bt: 'October to March', sl: 'fatehpur-sikri' },
  { n: 'Khajuraho Temples', sid: INS.mp, cid: '', d: 'The Khajuraho Group of Monuments is a collection of Hindu and Jain temples famous for erotic sculptures.', h: 'Built between 950 and 1050 CE by the Chandela dynasty.', cd: 'Originally 85 temples, only 25 survive today.', a: 'Nagara style with distinctive shikhara towers and intricate carvings.', vi: 'Open daily from sunrise to sunset.', lat: 24.851, lng: 79.9236, iu: '/images/monuments/khajuraho-temples.jpg', ius: '["/images/monuments/khajuraho-temples.jpg"]', bb: 'Chandela dynasty', bi: '950 - 1050 CE', sty: 'Nagara', na: '["Panna National Park","Dhuruvadhar Falls","Raneh Falls","Kalinjar Fort"]', ef: '₹40 for Indians, ₹600 for foreigners', ti: '6:00 AM - 6:00 PM', bt: 'October to March', sl: 'khajuraho-temples' },
  { n: 'Rani ki Vav', sid: INS.gujarat, cid: '', d: 'Rani ki Vav is an intricately constructed stepwell on the banks of the Saraswati River.', h: 'Built in the 11th century by Queen Udayamati in memory of her husband King Bhima I.', cd: 'The stepwell is 64 meters long, 20 meters wide, and 27 meters deep with seven levels.', a: 'Maru-Gurjara architecture with elaborate carved panels.', vi: 'Open daily from sunrise to sunset.', lat: 23.8588, lng: 72.0777, iu: '/images/monuments/rani-ki-vav.jpg', ius: '["/images/monuments/rani-ki-vav.jpg"]', bb: 'Queen Udayamati', bi: '11th century CE', sty: 'Maru-Gurjara', na: '["Somnath Temple","Dwarkadhish Temple","Gir National Park","Statue of Unity"]', ef: '₹35 for Indians, ₹550 for foreigners', ti: '7:00 AM - 6:00 PM', bt: 'October to March', sl: 'rani-ki-vav' },
  { n: 'Jaisalmer Fort', sid: INS.rajasthan, cid: '', d: 'Jaisalmer Fort is a living fort in the Thar Desert with golden sandstone walls.', h: 'Built in 1156 by Rawal Jaisal, withstanding numerous battles.', cd: 'Walls are 4.5 meters thick, rising 92 meters above the town with 99 bastions.', a: 'Rajput architecture with intricate lattice-work and filigree.', vi: 'Open daily. Best visited at sunset.', lat: 26.9124, lng: 70.9127, iu: '/images/monuments/jaisalmer-fort.jpg', ius: '["/images/monuments/jaisalmer-fort.jpg"]', bb: 'Rawal Jaisal', bi: '1156', sty: 'Rajput', na: '["Sam Sand Dunes","Patwon Ki Haveli","Gadisar Lake","Khuri Desert"]', ef: '₹50 for Indians, ₹250 for foreigners', ti: '9:00 AM - 6:00 PM', bt: 'October to March', sl: 'jaisalmer-fort' },
  { n: 'Golconda Fort', sid: INS.telangana, cid: '', d: 'Golconda Fort is a magnificent fortified citadel known for its advanced acoustic system.', h: 'Built by the Kakatiya dynasty in the 13th century, expanded by the Qutb Shahi sultans.', cd: 'Has eight gates, 87 bastions, and a unique clapping acoustic system.', a: 'Islamic architecture with massive granite walls.', vi: 'Open daily. Light and sound show in the evening.', lat: 17.3831, lng: 78.4011, iu: '/images/monuments/golconda-fort.jpg', ius: '["/images/monuments/golconda-fort.jpg"]', bb: 'Kakatiya and Qutb Shahi dynasties', bi: '13th - 16th century', sty: 'Islamic Deccani', na: '["Charminar","Hussain Sagar","Qutb Shahi Tombs","Taramati Baradari"]', ef: '₹25 for Indians, ₹300 for foreigners', ti: '9:00 AM - 5:30 PM', bt: 'October to March', sl: 'golconda-fort' },
  { n: 'Dakshineswar Temple', sid: INS.wb, cid: '', d: 'Dakshineswar Kali Temple is a historic Hindu temple dedicated to Goddess Kali on the Hooghly River.', h: 'Built in 1855 by Rani Rashmoni, associated with saint Ramakrishna.', cd: 'Includes the main temple with nine spires and twelve Shiva shrines.', a: 'Bengali Navaratna (nine-spired) architecture.', vi: 'Open daily. Best visited during evening aarti.', lat: 22.6558, lng: 88.3576, iu: '/images/monuments/dakshineswar-temple.jpg', ius: '["/images/monuments/dakshineswar-temple.jpg"]', bb: 'Rani Rashmoni', bi: '1855', sty: 'Bengali Navaratna', na: '["Belur Math","Howrah Bridge","Dakshineswar Kali Temple","Kalighat Temple"]', ef: 'Free', ti: '5:00 AM - 6:30 PM', bt: 'October to March', sl: 'dakshineswar-temple' },
  { n: 'Dilwara Temples', sid: INS.rajasthan, cid: '', d: 'The Dilwara Temples are a group of stunning Jain temples near Mount Abu with extraordinary marble carvings.', h: 'Built between the 11th and 13th centuries by ministers of the Solanki rulers.', cd: 'Each temple is built of white marble with exquisitely carved ceilings and pillars.', a: 'Maru-Gurjara Jain architecture with incredibly detailed marble carvings.', vi: 'Open daily. Photography not allowed inside.', lat: 24.5952, lng: 72.7165, iu: '/images/monuments/dilwara-temples.jpg', ius: '["/images/monuments/dilwara-temples.jpg"]', bb: 'Vimal Shah and other ministers', bi: '1031 - 1231 CE', sty: 'Maru-Gurjara Jain', na: '["Mount Abu","Nakki Lake","Guru Shikhar","Arbuda Devi Temple"]', ef: '₹10 for Indians, ₹500 for foreigners', ti: '8:00 AM - 5:00 PM', bt: 'November to February', sl: 'dilwara-temples' },
  { n: 'City Palace Udaipur', sid: INS.rajasthan, cid: '', d: 'The City Palace in Udaipur is a magnificent palace complex on the banks of Lake Pichola.', h: 'Construction began in 1559 by Maharana Udai Singh II, expanded over 400 years.', cd: '11 palaces connected by courtyards and terraces in granite and marble.', a: 'Rajput and Mughal architecture with intricate wall paintings and mirror work.', vi: 'Open daily. Light and sound show in the evening.', lat: 24.5768, lng: 73.6832, iu: '/images/monuments/city-palace-udaipur.jpg', ius: '["/images/monuments/city-palace-udaipur.jpg"]', bb: 'Maharana Udai Singh II', bi: '1559', sty: 'Rajput-Mughal', na: '["Lake Pichola","Jag Mandir","Sahelion Ki Bari","Fateh Sagar Lake"]', ef: '₹300 for Indians, ₹500 for foreigners', ti: '9:30 AM - 5:30 PM', bt: 'October to March', sl: 'city-palace-udaipur' },
];
for (const m of MONUMENTS_DATA) {
  insertMonument.run(generateId(), m.n, m.sid, m.cid, m.d, m.h, m.cd, m.a, m.vi, m.lat, m.lng, m.iu, m.ius, m.bb, m.bi, m.sty, m.na, m.ef, m.ti, m.bt, m.sl);
}

const FOODS_DATA = [
  { n: 'Biryani', sid: INS.telangana, cat: 'Main Course', d: 'A fragrant rice dish layered with marinated meat, saffron, and fried onions, cooked in a sealed pot.', h: 'Brought to India by Mughals and perfected in Hyderabad with local spices.', ing: '["Basmati rice","Chicken/Mutton","Yogurt","Onions","Saffron","Ghee","Spices"]', rv: '["Hyderabadi Biryani","Lucknowi Biryani","Kolkata Biryani","Malabar Biryani"]', iv: 0, sl: 'Medium', iu: '/images/foods/biryani.jpg', slug: 'biryani' },
  { n: 'Butter Chicken', sid: INS.delhi, cat: 'Main Course', d: 'Tender chicken pieces in a rich, creamy tomato-based sauce with butter and aromatic spices.', h: 'Invented in the 1950s at Moti Mahal restaurant in Delhi by Kundan Lal Gujral.', ing: '["Chicken","Butter","Tomatoes","Cream","Spices","Ginger-Garlic"]', rv: '["Punjabi Butter Chicken","Delhi Butter Chicken","Creamy Restaurant Style"]', iv: 0, sl: 'Medium', iu: '/images/foods/butter-chicken.jpg', slug: 'butter-chicken' },
  { n: 'Dosa', sid: INS.tn, cat: 'Main Course', d: 'A thin, crispy fermented crepe made from rice and urad dal batter, served with chutneys and sambhar.', h: 'Originated in South India over 1000 years ago, mentioned in ancient Tamil literature.', ing: '["Rice","Urad Dal","Fenugreek Seeds","Salt","Oil/Ghee"]', rv: '["Masala Dosa","Rava Dosa","Paper Dosa","Set Dosa","Onion Dosa"]', iv: 1, sl: 'Low', iu: '/images/foods/dosa.jpg', slug: 'dosa' },
  { n: 'Vada Pav', sid: INS.maharashtra, cat: 'Street Food', d: 'A spicy potato fritter sandwiched in a bread bun with green chutney and fried green chili.', h: 'Originated as an affordable street food in Mumbai and became the city\'s iconic fast food.', ing: '["Potato","Pav (Bread)","Gram Flour Batter","Green Chutney","Garlic Chutney"]', rv: '["Mumbai Vada Pav","Pune Vada Pav","Cheese Vada Pav"]', iv: 1, sl: 'Medium', iu: '/images/foods/vada-pav.jpg', slug: 'vada-pav' },
  { n: 'Pav Bhaji', sid: INS.maharashtra, cat: 'Street Food', d: 'A spicy mash of mixed vegetables served with butter-toasted bread rolls.', h: 'Created in Mumbai as a quick nutritious meal for textile mill workers.', ing: '["Mixed Vegetables","Pav Bhaji Masala","Butter","Onions","Tomatoes","Pav"]', rv: '["Mumbai Pav Bhaji","Cheese Pav Bhaji","Punjabi Pav Bhaji"]', iv: 1, sl: 'Medium', iu: '/images/foods/pav-bhaji.jpg', slug: 'pav-bhaji' },
  { n: 'Dhokla', sid: INS.gujarat, cat: 'Snack', d: 'A soft, spongy steamed snack made from fermented gram flour batter.', h: 'A traditional Gujarati dish that has been part of the cuisine for centuries.', ing: '["Gram Flour (Besan)","Yogurt","Green Chilies","Ginger","Mustard Seeds","Curry Leaves"]', rv: '["Khaman Dhokla","Khandvi","Nylon Dhokla","Rava Dhokla"]', iv: 1, sl: 'Low', iu: '/images/foods/dhokla.jpg', slug: 'dhokla' },
  { n: 'Litti Chokha', sid: INS.bihar, cat: 'Main Course', d: 'Roasted wheat flour balls stuffed with spiced sattu served with mashed eggplant and tomato chokha.', h: 'A traditional Bihari staple that originated as a nutritious meal for farmers.', ing: '["Wheat Flour","Sattu","Eggplant","Tomatoes","Mustard Oil","Garlic"]', rv: '["Bihari Litti","Jharkhandi Litti","Banarasi Litti"]', iv: 1, sl: 'Medium', iu: '/images/foods/litti-chokha.jpg', slug: 'litti-chokha' },
  { n: 'Rogan Josh', sid: INS.jk, cat: 'Main Course', d: 'An aromatic lamb curry with a rich red gravy made from Kashmiri red chilies.', h: 'Brought to Kashmir by the Mughals, a signature of Kashmiri Wazwan cuisine.', ing: '["Lamb","Yogurt","Kashmiri Red Chili","Fennel","Ginger","Garlic","Spices"]', rv: '["Kashmiri Rogan Josh","Punjabi Rogan Josh","Hyderabadi Rogan Josh"]', iv: 0, sl: 'Medium', iu: '/images/foods/rogan-josh.jpg', slug: 'rogan-josh' },
  { n: 'Hyderabadi Biryani', sid: INS.telangana, cat: 'Main Course', d: 'A legendary rice dish with marinated meat cooked in a dum pot with saffron.', h: 'Developed in the kitchens of the Nizams of Hyderabad.', ing: '["Basmati Rice","Chicken/Mutton","Yogurt","Saffron","Fried Onions","Spices","Ghee"]', rv: '["Hyderabadi Chicken Biryani","Hyderabadi Mutton Biryani","Hyderabadi Veg Biryani"]', iv: 0, sl: 'Medium', iu: '/images/foods/hyderabadi-biryani.jpg', slug: 'hyderabadi-biryani' },
  { n: 'Masala Dosa', sid: INS.karnataka, cat: 'Main Course', d: 'A crispy rice and lentil crepe filled with spiced potato filling.', h: 'Originated in the Udupi region of Karnataka.', ing: '["Rice","Urad Dal","Potato","Onions","Green Chilies","Mustard Seeds","Turmeric"]', rv: '["Mysore Masala Dosa","Rava Masala Dosa","Paper Masala Dosa"]', iv: 1, sl: 'Low', iu: '/images/foods/masala-dosa.jpg', slug: 'masala-dosa' },
  { n: 'Pongal', sid: INS.tn, cat: 'Main Course', d: 'A comforting rice and lentil dish tempered with black pepper, cumin, and cashews.', h: 'Traditionally prepared during the Pongal harvest festival.', ing: '["Rice","Moong Dal","Black Pepper","Cumin","Cashews","Ghee","Ginger"]', rv: '["Ven Pongal","Sakkarai Pongal","Kerala Pongal"]', iv: 1, sl: 'Low', iu: '/images/foods/pongal.jpg', slug: 'pongal' },
  { n: 'Fish Curry', sid: INS.wb, cat: 'Main Course', d: 'A delicate fish curry made in a light mustard and turmeric gravy.', h: 'Bengal\'s riverine geography made fish a dietary staple.', ing: '["Fish (Rohu/Hilsa)","Mustard Seeds","Turmeric","Green Chilies","Mustard Oil","Poppy Seeds"]', rv: '["Bengali Macher Jhol","Malabar Fish Curry","Goan Fish Curry","Kerala Fish Curry"]', iv: 0, sl: 'Medium', iu: '/images/foods/fish-curry.jpg', slug: 'fish-curry' },
  { n: 'Rasgulla', sid: INS.wb, cat: 'Dessert', d: 'Soft, spongy cottage cheese balls soaked in light sugar syrup.', h: 'Invented in Kolkata by confectioner Nobin Chandra Das in 1868.', ing: '["Chhena (Cottage Cheese)","Sugar","Rose Water","Cardamom"]', rv: '["Bengali Rasgulla","Odisha Rasgulla","Sponge Rasgulla"]', iv: 1, sl: 'Low', iu: '/images/foods/rasgulla.jpg', slug: 'rasgulla' },
  { n: 'Gulab Jamun', sid: INS.rajasthan, cat: 'Dessert', d: 'Deep-fried milk solid dumplings soaked in rose-flavored sugar syrup.', h: 'Originated in medieval India, influenced by Persian cuisine.', ing: '["Milk Powder","Flour","Ghee","Sugar","Rose Water","Cardamom","Saffron"]', rv: '["Kala Jamun","Gulab Jamun with Rabri","Dry Gulab Jamun"]', iv: 1, sl: 'Low', iu: '/images/foods/gulab-jamun.jpg', slug: 'gulab-jamun' },
  { n: 'Jalebi', sid: INS.rajasthan, cat: 'Dessert', d: 'Crispy, pretzel-shaped batter deep-fried and soaked in saffron-scented sugar syrup.', h: 'One of the oldest Indian sweets, mentioned in ancient texts.', ing: '["All-Purpose Flour","Yogurt","Sugar","Saffron","Cardamom","Ghee"]', rv: '["Imarti","Jangiri","Kesaria Jalebi"]', iv: 1, sl: 'Low', iu: '/images/foods/jalebi.jpg', slug: 'jalebi' },
  { n: 'Kulfi', sid: INS.delhi, cat: 'Dessert', d: 'A dense, creamy frozen dessert made from reduced milk.', h: 'Originated during the Mughal era as a royal frozen treat.', ing: '["Full Cream Milk","Sugar","Cardamom","Saffron","Pistachios","Almonds"]', rv: '["Mango Kulfi","Malai Kulfi","Pista Kulfi","Rose Kulfi"]', iv: 1, sl: 'Low', iu: '/images/foods/kulfi.jpg', slug: 'kulfi' },
  { n: 'Samosa', sid: INS.delhi, cat: 'Snack', d: 'A crispy fried pastry triangle filled with spiced potatoes and peas.', h: 'Introduced to India by Middle Eastern traders during the Delhi Sultanate.', ing: '["All-Purpose Flour","Potato","Peas","Cumin","Coriander","Ginger","Green Chilies"]', rv: '["Punjabi Samosa","Lucknowi Samosa","Sindhi Samosa","Chicken Samosa"]', iv: 1, sl: 'Medium', iu: '/images/foods/samosa.jpg', slug: 'samosa' },
  { n: 'Aloo Tikki', sid: INS.delhi, cat: 'Snack', d: 'Crispy fried potato patties seasoned with spices.', h: 'A popular North Indian street food that has become a staple chaat item.', ing: '["Potato","Cornflour","Cumin","Chaat Masala","Ginger","Green Chilies"]', rv: '["Aloo Tikki Chaat","Ragda Patties","Chole Tikki"]', iv: 1, sl: 'Medium', iu: '/images/foods/aloo-tikki.jpg', slug: 'aloo-tikki' },
  { n: 'Chole Bhature', sid: INS.delhi, cat: 'Main Course', d: 'Spicy chickpea curry served with deep-fried fluffy bread.', h: 'Originated in the Punjab region and popularized in Delhi.', ing: '["Chickpeas","Chole Masala","Onions","Tomatoes","Ginger","All-Purpose Flour","Yogurt"]', rv: '["Amritsari Chole","Delhi Chole Bhature","Kulcha Chole"]', iv: 1, sl: 'High', iu: '/images/foods/chole-bhature.jpg', slug: 'chole-bhature' },
  { n: 'Paratha', sid: INS.punjab, cat: 'Main Course', d: 'A flaky, layered flatbread made from whole wheat flour.', h: 'A staple of North Indian cuisine with stuffed variations.', ing: '["Whole Wheat Flour","Ghee","Potato/Cauliflower/Radish","Spices"]', rv: '["Aloo Paratha","Gobi Paratha","Paneer Paratha","Mooli Paratha","Lachha Paratha"]', iv: 1, sl: 'Low', iu: '/images/foods/paratha.jpg', slug: 'paratha' },
  { n: 'Naan', sid: INS.delhi, cat: 'Main Course', d: 'A soft, leavened flatbread baked in a tandoor.', h: 'Originated in the Mughal courts.', ing: '["All-Purpose Flour","Yogurt","Milk","Yeast","Ghee","Nigella Seeds"]', rv: '["Butter Naan","Garlic Naan","Peshawari Naan","Keema Naan"]', iv: 1, sl: 'Low', iu: '/images/foods/naan.jpg', slug: 'naan' },
  { n: 'Tandoori Chicken', sid: INS.delhi, cat: 'Main Course', d: 'Chicken marinated in yogurt and spices, cooked in a tandoor.', h: 'Introduced by Kundan Lal Gujral, a chef from Peshawar.', ing: '["Chicken","Yogurt","Tandoori Masala","Ginger-Garlic Paste","Lemon","Ghee"]', rv: '["Chicken Tikka","Tangri Kebab","Malai Tikka"]', iv: 0, sl: 'Medium', iu: '/images/foods/tandoori-chicken.jpg', slug: 'tandoori-chicken' },
  { n: 'Dal Makhani', sid: INS.delhi, cat: 'Main Course', d: 'Rich, creamy black lentils slow-cooked with butter and cream.', h: 'Originated in Punjab, a signature dish of North Indian dhabas.', ing: '["Whole Black Lentils","Kidney Beans","Butter","Cream","Tomatoes","Ginger","Garlic"]', rv: '["Punjabi Dal Makhani","Maa Ki Dal","Restaurant Style Dal Makhani"]', iv: 1, sl: 'Low', iu: '/images/foods/dal-makhani.jpg', slug: 'dal-makhani' },
  { n: 'Palak Paneer', sid: INS.punjab, cat: 'Main Course', d: 'Cottage cheese cubes in a smooth, spiced spinach gravy.', h: 'A staple of Punjabi cuisine popular across India.', ing: '["Spinach","Paneer","Onions","Tomatoes","Cream","Ginger","Garlic","Spices"]', rv: '["Palak Paneer","Saag Paneer","Methi Paneer"]', iv: 1, sl: 'Low', iu: '/images/foods/palak-paneer.jpg', slug: 'palak-paneer' },
  { n: 'Idli', sid: INS.tn, cat: 'Main Course', d: 'Soft, steamed savory rice cakes made from fermented rice and urad dal batter.', h: 'Mentioned in Kannada literature from the 10th century.', ing: '["Rice","Urad Dal","Fenugreek Seeds","Salt"]', rv: '["Rava Idli","Malli Idli","Kanchipuram Idli","Oats Idli"]', iv: 1, sl: 'Low', iu: '/images/foods/idli.jpg', slug: 'idli' },
  { n: 'Sambhar', sid: INS.tn, cat: 'Main Course', d: 'A spicy lentil and vegetable stew tempered with mustard seeds and curry leaves.', h: 'Originated in Tamil Nadu, named after Sambhaji.', ing: '["Toor Dal","Mixed Vegetables","Sambhar Masala","Tamarind","Mustard Seeds","Curry Leaves"]', rv: '["Tamil Sambhar","Kerala Sambhar","Udupi Sambhar","Poddi Sambhar"]', iv: 1, sl: 'Medium', iu: '/images/foods/sambhar.jpg', slug: 'sambhar' },
  { n: 'Vada', sid: INS.tn, cat: 'Snack', d: 'Deep-fried lentil donuts, crispy outside and soft inside.', h: 'A traditional South Indian snack mentioned in ancient Tamil literature.', ing: '["Urad Dal","Curry Leaves","Green Chilies","Ginger","Black Pepper","Coconut"]', rv: '["Medu Vada","Masala Vada","Kerala Vada","Maddur Vada"]', iv: 1, sl: 'Low', iu: '/images/foods/vada.jpg', slug: 'vada' },
  { n: 'Bhel Puri', sid: INS.maharashtra, cat: 'Street Food', d: 'A tangy, crunchy snack made of puffed rice, sev, peanuts, and vegetables.', h: 'Originated on the beaches of Mumbai.', ing: '["Puffed Rice","Sev","Peanuts","Onions","Tomatoes","Tamarind Chutney","Cilantro"]', rv: '["Mumbai Bhel","Punjabi Bhel","Jhal Muri"]', iv: 1, sl: 'Medium', iu: '/images/foods/bhel-puri.jpg', slug: 'bhel-puri' },
  { n: 'Panipuri', sid: INS.delhi, cat: 'Street Food', d: 'Crispy hollow puris filled with spiced potato and tangy tamarind-flavored water.', h: 'Originated in the Magadha region over 2000 years ago.', ing: '["Semolina Puri","Potato","Chickpeas","Tamarind","Mint","Coriander","Spices"]', rv: '["Golgappa (North)","Pani Patashi (Rajasthan)","Gupchup (East)","Pani Puri (West/South)"]', iv: 1, sl: 'Medium', iu: '/images/foods/panipuri.jpg', slug: 'panipuri' },
  { n: 'Dahi Bhalla', sid: INS.delhi, cat: 'Snack', d: 'Soft lentil fritters soaked in creamy yogurt with tamarind chutney.', h: 'A beloved chaat item from North India.', ing: '["Urad Dal","Yogurt","Tamarind Chutney","Green Chutney","Chaat Masala","Cumin Powder"]', rv: '["Dahi Bhalla","Dahi Vada","Dahi Balle"]', iv: 1, sl: 'Low', iu: '/images/foods/dahi-bhalla.jpg', slug: 'dahi-bhalla' },
];
for (const f of FOODS_DATA) {
  insertFood.run(generateId(), f.n, f.sid, f.cat, f.d, f.h, f.ing, f.rv, f.iv, f.sl, f.iu, f.slug);
}

const FESTIVALS_DATA = [
  { n: 'Diwali', sid: INS.up, d: 'The festival of lights, celebrating the return of Lord Rama to Ayodhya.', m: 'October-November', da: 'Varies', t: '["Lighting diyas","Fireworks","Rangoli","Puja","Gift exchanges"]', nh: 1, ty: 'Religious', iu: '/images/festivals/diwali.jpg', sl: 'diwali' },
  { n: 'Holi', sid: INS.up, d: 'The festival of colors, celebrating the arrival of spring.', m: 'March', da: 'Full moon of Phalguna', t: '["Playing with colors","Water balloons","Dhol music","Gujiya sweets"]', nh: 0, ty: 'Religious', iu: '/images/festivals/holi.jpg', sl: 'holi' },
  { n: 'Dussehra', sid: INS.up, d: 'Celebrates Lord Rama\'s victory over the demon king Ravana.', m: 'October', da: '10th day of Ashwin', t: '["Ravan effigy burning","Ram Leela","Processions"]', nh: 1, ty: 'Religious', iu: '/images/festivals/dussehra.jpg', sl: 'dussehra' },
  { n: 'Eid', sid: INS.delhi, d: 'The festival marking the end of Ramadan.', m: 'Varies', da: 'Based on Islamic calendar', t: '["Eid prayers","Zakat","Feasts","Gift giving","New clothes"]', nh: 1, ty: 'Religious', iu: '/images/festivals/eid.jpg', sl: 'eid' },
  { n: 'Christmas', sid: INS.goa, d: 'Celebration of the birth of Jesus Christ.', m: 'December', da: 'December 25', t: '["Midnight mass","Christmas tree","Gift exchange","Carols"]', nh: 1, ty: 'Religious', iu: '/images/festivals/christmas.jpg', sl: 'christmas' },
  { n: 'Pongal', sid: INS.tn, d: 'The harvest festival thanking the Sun God.', m: 'January', da: 'January 14-17', t: '["Pongal preparation","Kolam designs","Cattle decoration","Bonfires"]', nh: 0, ty: 'Harvest', iu: '/images/festivals/pongal.jpg', sl: 'pongal' },
  { n: 'Baisakhi', sid: INS.punjab, d: 'The harvest festival celebrating the Sikh New Year.', m: 'April', da: 'April 13-14', t: '["Nagarkirtan","Bhangra","Gurdwara visits","Community meals"]', nh: 0, ty: 'Harvest', iu: '/images/festivals/baisakhi.jpg', sl: 'baisakhi' },
  { n: 'Onam', sid: INS.kerala, d: 'The harvest festival celebrating King Mahabali\'s homecoming.', m: 'August-September', da: 'Varies', t: '["Pookalam flowers","Onam Sadya","Vallam Kali boat race","Thiruvathira"]', nh: 0, ty: 'Harvest', iu: '/images/festivals/onam.jpg', sl: 'onam' },
  { n: 'Durga Puja', sid: INS.wb, d: 'The grand festival honoring Goddess Durga\'s victory over Mahishasura.', m: 'September-October', da: '5 days in Ashwin', t: '["Pandals","Idol immersion","Dhunuchi dance","Sindur Khela"]', nh: 0, ty: 'Religious', iu: '/images/festivals/durga-puja.jpg', sl: 'durga-puja' },
  { n: 'Ganesh Chaturthi', sid: INS.maharashtra, d: 'The festival celebrating the birth of Lord Ganesha.', m: 'August-September', da: '4th day of Bhadrapada', t: '["Idol installation","Modak offerings","Processions","Immersion"]', nh: 0, ty: 'Religious', iu: '/images/festivals/ganesh-chaturthi.jpg', sl: 'ganesh-chaturthi' },
  { n: 'Navratri', sid: INS.gujarat, d: 'A nine-night festival honoring the divine feminine with Garba and Dandiya.', m: 'September-October', da: '9 days in Ashwin', t: '["Garba","Dandiya","Fasting","Kanya Pujan"]', nh: 0, ty: 'Religious', iu: '/images/festivals/navratri.jpg', sl: 'navratri' },
  { n: 'Makar Sankranti', sid: INS.andhra, d: 'The harvest festival marking the sun\'s transition into Capricorn.', m: 'January', da: 'January 14-15', t: '["Kite flying","Til-gul sweets","Holy dips","Bonfires"]', nh: 0, ty: 'Harvest', iu: '/images/festivals/makar-sankranti.jpg', sl: 'makar-sankranti' },
  { n: 'Ugadi', sid: INS.karnataka, d: 'The Telugu and Kannada New Year celebrated in the Deccan region.', m: 'March-April', da: 'First day of Chaitra', t: '["Ugadi Pachadi","Mango decorations","New year rituals"]', nh: 0, ty: 'Cultural', iu: '/images/festivals/ugadi.jpg', sl: 'ugadi' },
  { n: 'Gudi Padwa', sid: INS.maharashtra, d: 'The Marathi New Year celebrated with the hoisting of the Gudi flag.', m: 'March-April', da: 'First day of Chaitra', t: '["Gudi hoisting","Rangoli","Puran Poli","Processions"]', nh: 0, ty: 'Cultural', iu: '/images/festivals/gudi-padwa.jpg', sl: 'gudi-padwa' },
  { n: 'Lohri', sid: INS.punjab, d: 'A winter harvest festival celebrated with bonfires and dancing.', m: 'January', da: 'January 13', t: '["Bonfire","Bhangra","Peanuts and rewari","Folk songs"]', nh: 0, ty: 'Harvest', iu: '/images/festivals/lohri.jpg', sl: 'lohri' },
  { n: 'Janmashtami', sid: INS.gujarat, d: 'The celebration of Lord Krishna\'s birth with Dahi Handi events.', m: 'August-September', da: '8th day of Bhadrapada', t: '["Dahi Handi","Midnight puja","Rasa Lila","Fasting"]', nh: 0, ty: 'Religious', iu: '/images/festivals/janmashtami.jpg', sl: 'janmashtami' },
  { n: 'Good Friday', sid: INS.goa, d: 'Christian festival commemorating the crucifixion of Jesus Christ.', m: 'March-April', da: 'Friday before Easter', t: '["Church services","Processions","Fasting"]', nh: 1, ty: 'Religious', iu: '/images/festivals/good-friday.jpg', sl: 'good-friday' },
  { n: 'Mahavir Jayanti', sid: INS.rajasthan, d: 'The birth anniversary of Lord Mahavira, the 24th Tirthankara of Jainism.', m: 'March-April', da: '13th day of Chaitra', t: '["Temple visits","Processions","Charity","Lectures"]', nh: 0, ty: 'Religious', iu: '/images/festivals/mahavir-jayanti.jpg', sl: 'mahavir-jayanti' },
  { n: 'Buddha Purnima', sid: INS.bihar, d: 'The birth, enlightenment, and death anniversary of Gautama Buddha.', m: 'April-May', da: 'Full moon of Vaisakha', t: '["Temple visits","Meditation","Sermons","Vegetarian meals"]', nh: 0, ty: 'Religious', iu: '/images/festivals/buddha-purnima.jpg', sl: 'buddha-purnima' },
  { n: 'Guru Nanak Jayanti', sid: INS.punjab, d: 'The birth anniversary of Guru Nanak Dev, founder of Sikhism.', m: 'November', da: 'Full moon of Kartik', t: '["Prabhat Pheri","Akhand Path","Langar","Processions"]', nh: 0, ty: 'Religious', iu: '/images/festivals/guru-nanak-jayanti.jpg', sl: 'guru-nanak-jayanti' },
  { n: 'Raksha Bandhan', sid: INS.rajasthan, d: 'The festival celebrating the bond between brothers and sisters.', m: 'August', da: 'Full moon of Shravana', t: '["Rakhi tying","Gift exchange","Family gatherings","Traditional sweets"]', nh: 0, ty: 'Cultural', iu: '/images/festivals/raksha-bandhan.jpg', sl: 'raksha-bandhan' },
  { n: 'Karva Chauth', sid: INS.rajasthan, d: 'A fasting ritual observed by married women for their husbands\' longevity.', m: 'October-November', da: '4th day after Kartik full moon', t: '["Day-long fast","Sargi meal","Moon sighting","Puja"]', nh: 0, ty: 'Cultural', iu: '/images/festivals/karva-chauth.jpg', sl: 'karva-chauth' },
];
for (const f of FESTIVALS_DATA) {
  insertFestival.run(generateId(), f.n, f.sid, f.d, f.m, f.da, f.t, f.nh, f.ty, f.iu, f.sl);
}

const EVENTS_DATA = [
  { t: 'Indus Valley Civilization', d: 'One of the world\'s oldest urban civilizations, flourishing in the Indus River Valley with advanced city planning.', da: '3300 BCE - 1300 BCE', y: -3300, p: 'Ancient', c: 'Ancient Civilization', pers: '[]', loc: '["Harappa","Mohenjo-Daro","Dholavira","Rakhigarhi"]', iu: '/images/events/indus-valley.jpg' },
  { t: 'Vedic Period', d: 'The period of the composition of the Vedas, the oldest sacred texts of Hinduism.', da: '1500 BCE - 500 BCE', y: -1500, p: 'Ancient', c: 'Ancient Civilization', pers: '[]', loc: '["Sapta Sindhu","Ganges Plain"]', iu: '/images/events/vedic-period.jpg' },
  { t: 'Rise of Buddhism and Jainism', d: 'The 6th century BCE saw the rise of Buddhism and Jainism as reform movements.', da: '6th Century BCE', y: -600, p: 'Ancient', c: 'Religious', pers: '["Gautama Buddha","Mahavira"]', loc: '["Bodh Gaya","Lumbini","Sarnath","Kushinagar"]', iu: '/images/events/buddha-mahavira.jpg' },
  { t: 'Maurya Empire Foundation', d: 'Chandragupta Maurya founded the first empire to unify most of the Indian subcontinent.', da: '322 BCE', y: -322, p: 'Ancient', c: 'Empire', pers: '["Chandragupta Maurya","Chanakya"]', loc: '["Pataliputra","Magadha"]', iu: '/images/events/maurya-empire.jpg' },
  { t: 'Ashoka the Great', d: 'Emperor Ashoka embraced Buddhism after the Kalinga War and spread its teachings across Asia.', da: '268 BCE - 232 BCE', y: -268, p: 'Ancient', c: 'Empire', pers: '["Ashoka the Great"]', loc: '["Kalinga","Pataliputra","Sanchi"]', iu: '/images/events/ashoka.jpg' },
  { t: 'Gupta Empire Golden Age', d: 'The Gupta period is considered the golden age of India with advancements in science and literature.', da: '320 CE - 550 CE', y: 320, p: 'Ancient', c: 'Empire', pers: '["Samudragupta","Chandragupta II","Kalidas"]', loc: '["Pataliputra","Ujjain","Nalanda"]', iu: '/images/events/gupta-empire.jpg' },
  { t: 'Harsha Kingdom', d: 'King Harsha unified northern India and was known for his patronage of Buddhism.', da: '606 CE - 647 CE', y: 606, p: 'Ancient', c: 'Empire', pers: '["Harshavardhana","Xuanzang"]', loc: '["Kannauj","Thanesar","Nalanda"]', iu: '/images/events/harsha-kingdom.jpg' },
  { t: 'Chola Empire', d: 'The Chola dynasty became a maritime superpower ruling South India and Southeast Asia.', da: '850 CE - 1279 CE', y: 850, p: 'Ancient', c: 'Empire', pers: '["Raja Raja Chola I","Rajendra Chola I"]', loc: '["Thanjavur","Gangaikonda Cholapuram","Sri Lanka","Sumatra"]', iu: '/images/events/chola-empire.jpg' },
  { t: 'Rashtrakuta Dynasty', d: 'The Rashtrakutas ruled the Deccan and built the Kailasa Temple at Ellora.', da: '753 CE - 982 CE', y: 753, p: 'Ancient', c: 'Empire', pers: '["Dantidurga","Amoghavarsha"]', loc: '["Manyakheta","Ellora"]', iu: '/images/events/rashtrakuta.jpg' },
  { t: 'Delhi Sultanate', d: 'The Delhi Sultanate established Muslim rule in North India with successive dynasties.', da: '1206 CE - 1526 CE', y: 1206, p: 'Medieval', c: 'Empire', pers: '["Qutb-ud-din Aibak","Alauddin Khilji","Muhammad bin Tughlaq"]', loc: '["Delhi","Daulatabad","Warangal"]', iu: '/images/events/delhi-sultanate.jpg' },
  { t: 'Khilji Dynasty', d: 'The Khilji dynasty expanded the Delhi Sultanate southward and repelled Mongol invasions.', da: '1290 CE - 1320 CE', y: 1290, p: 'Medieval', c: 'Empire', pers: '["Alauddin Khilji","Malik Kafur"]', loc: '["Delhi","Devagiri","Madurai"]', iu: '/images/events/khilji-dynasty.jpg' },
  { t: 'Tughlaq Dynasty', d: 'Known for ambitious projects and shifting the capital from Delhi to Daulatabad.', da: '1320 CE - 1414 CE', y: 1320, p: 'Medieval', c: 'Empire', pers: '["Ghiyasuddin Tughlaq","Muhammad bin Tughlaq","Firuz Shah Tughlaq"]', loc: '["Delhi","Daulatabad"]', iu: '/images/events/tughlaq-dynasty.jpg' },
  { t: 'Vijayanagara Empire', d: 'The Vijayanagara Empire ruled the Deccan and South India from its capital Hampi.', da: '1336 CE - 1646 CE', y: 1336, p: 'Medieval', c: 'Empire', pers: '["Harihara I","Bukka Raya I","Krishnadevaraya"]', loc: '["Hampi","Penukonda","Chandragiri"]', iu: '/images/events/vijayanagara.jpg' },
  { t: 'Mughal Empire Foundation', d: 'Babur founded the Mughal Empire after defeating the Delhi Sultanate at Panipat.', da: '1526 CE', y: 1526, p: 'Medieval', c: 'Empire', pers: '["Babur","Ibrahim Lodi"]', loc: '["Panipat","Agra","Delhi"]', iu: '/images/events/mughal-foundation.jpg' },
  { t: 'Reign of Akbar the Great', d: 'Emperor Akbar expanded the Mughal Empire and introduced policies of religious tolerance.', da: '1556 CE - 1605 CE', y: 1556, p: 'Medieval', c: 'Empire', pers: '["Akbar the Great","Birbal","Todar Mal","Mansingh"]', loc: '["Fatehpur Sikri","Agra","Delhi","Lahore"]', iu: '/images/events/akbar.jpg' },
  { t: 'Shah Jahan Period', d: 'Emperor Shah Jahan built the Taj Mahal and ushered the peak of Mughal architecture.', da: '1628 CE - 1658 CE', y: 1628, p: 'Medieval', c: 'Empire', pers: '["Shah Jahan","Mumtaz Mahal"]', loc: '["Agra","Delhi","Lahore"]', iu: '/images/events/shah-jahan.jpg' },
  { t: 'Aurangzeb Reign', d: 'The last great Mughal emperor who expanded the empire to its greatest territorial extent.', da: '1658 CE - 1707 CE', y: 1658, p: 'Medieval', c: 'Empire', pers: '["Aurangzeb"]', loc: '["Delhi","Aurangabad","Deccan"]', iu: '/images/events/aurangzeb.jpg' },
  { t: 'Maratha Empire under Shivaji', d: 'Shivaji Maharaj founded the Maratha Empire and established Hindavi Swaraj through guerilla warfare.', da: '1674 CE - 1680 CE', y: 1674, p: 'Medieval', c: 'Empire', pers: '["Shivaji Maharaj","Sambhaji"]', loc: '["Raigad","Pune","Sinhagad","Pratapgad"]', iu: '/images/events/shivaji.jpg' },
  { t: 'Arrival of Vasco da Gama', d: 'Portuguese explorer Vasco da Gama reached Calicut, establishing the first sea route from Europe to India.', da: '1498', y: 1498, p: 'Colonial', c: 'Exploration', pers: '["Vasco da Gama","Zamorin"]', loc: '["Calicut (Kozhikode)"]', iu: '/images/events/vasco-da-gama.jpg' },
  { t: 'British East India Company', d: 'The East India Company was granted Royal Charter to trade with India, eventually becoming a colonial power.', da: '1600', y: 1600, p: 'Colonial', c: 'Colonial Power', pers: '["Queen Elizabeth I","Robert Clive"]', loc: '["London","Surat","Madras","Bombay","Calcutta"]', iu: '/images/events/east-india-company.jpg' },
  { t: 'Battle of Plassey', d: 'Robert Clive\'s victory over Nawab Siraj-ud-Daulah established British dominance in Bengal.', da: 'June 23, 1757', y: 1757, p: 'Colonial', c: 'Battle', pers: '["Robert Clive","Siraj-ud-Daulah","Mir Jafar"]', loc: '["Plassey","Bengal"]', iu: '/images/events/battle-of-plassey.jpg' },
  { t: 'Battle of Buxar', d: 'The British East India Company defeated the combined forces of Mughal emperor, Nawab of Bengal, and Nawab of Awadh.', da: 'October 22, 1764', y: 1764, p: 'Colonial', c: 'Battle', pers: '["Hector Munro","Shah Alam II","Mir Qasim"]', loc: '["Buxar","Bihar"]', iu: '/images/events/battle-of-buxar.jpg' },
  { t: 'Anglo-Mysore Wars', d: 'Four wars between the British East India Company and the Kingdom of Mysore under Hyder Ali and Tipu Sultan.', da: '1767 - 1799', y: 1767, p: 'Colonial', c: 'War', pers: '["Tipu Sultan","Hyder Ali","Lord Cornwallis"]', loc: '["Mysore","Srirangapatna"]', iu: '/images/events/anglo-mysore-wars.jpg' },
  { t: 'Anglo-Maratha Wars', d: 'Three wars between the British East India Company and the Maratha Empire leading to British supremacy in India.', da: '1775 - 1818', y: 1775, p: 'Colonial', c: 'War', pers: '["Lord Hastings","Peshwa Baji Rao II","Mahadaji Shinde"]', loc: '["Pune","Delhi","Central India"]', iu: '/images/events/anglo-maratha-wars.jpg' },
  { t: 'Revolt of 1857', d: 'India\'s first major uprising against British rule, known as the Sepoy Mutiny.', da: 'May 10, 1857 - November 1, 1858', y: 1857, p: 'Colonial', c: 'Rebellion', pers: '["Mangal Pandey","Rani Lakshmibai","Bahadur Shah Zafar","Nana Sahib"]', loc: '["Meerut","Delhi","Kanpur","Jhansi","Lucknow"]', iu: '/images/events/revolt-1857.jpg' },
  { t: 'Formation of Indian National Congress', d: 'The INC was founded to provide a platform for Indians to voice political concerns and demand representation.', da: 'December 28, 1885', y: 1885, p: 'Independence', c: 'Political', pers: '["A.O. Hume","W.C. Banerjee","Dadabhai Naoroji"]', loc: '["Bombay","Gokuldas Tejpal Sanskrit College"]', iu: '/images/events/inc-formation.jpg' },
  { t: 'Partition of Bengal', d: 'The British partitioned Bengal on communal lines, sparking widespread protests and the Swadeshi movement.', da: 'October 16, 1905', y: 1905, p: 'Independence', c: 'Political Event', pers: '["Lord Curzon","Rabindranath Tagore","Surendranath Banerjee"]', loc: '["Bengal","Calcutta","Dhaka"]', iu: '/images/events/partition-of-bengal.jpg' },
  { t: 'Jallianwala Bagh Massacre', d: 'British troops fired on unarmed civilians gathered for a peaceful protest in Amritsar.', da: 'April 13, 1919', y: 1919, p: 'Independence', c: 'Massacre', pers: '["General Dyer","Udham Singh"]', loc: '["Amritsar","Punjab"]', iu: '/images/events/jallianwala-bagh.jpg' },
  { t: 'Non-Cooperation Movement', d: 'Gandhi launched the first mass civil disobedience movement against British rule.', da: 'September 5, 1920 - February 12, 1922', y: 1920, p: 'Independence', c: 'Movement', pers: '["Mahatma Gandhi","Jawaharlal Nehru","C.R. Das"]', loc: '["All India"]', iu: '/images/events/non-cooperation.jpg' },
  { t: 'Civil Disobedience Movement', d: 'The famous Dandi March led by Gandhi to break the salt law, sparking nationwide protests.', da: 'March 12, 1930 - April 6, 1930', y: 1930, p: 'Independence', c: 'Movement', pers: '["Mahatma Gandhi","Sarojini Naidu"]', loc: '["Sabarmati Ashram","Dandi","All India"]', iu: '/images/events/dandi-march.jpg' },
  { t: 'Quit India Movement', d: 'Gandhi called for the British to leave India with the slogan Do or Die, leading to mass arrests.', da: 'August 8, 1942 - 1945', y: 1942, p: 'Independence', c: 'Movement', pers: '["Mahatma Gandhi","Jawaharlal Nehru","Subhas Chandra Bose"]', loc: '["Bombay","All India"]', iu: '/images/events/quit-india.jpg' },
  { t: 'Indian Independence Act 1947', d: 'India gained independence from British rule and was partitioned into India and Pakistan.', da: 'August 15, 1947', y: 1947, p: 'Independence', c: 'Independence', pers: '["Jawaharlal Nehru","Mahatma Gandhi","Lord Mountbatten","Muhammad Ali Jinnah"]', loc: '["Delhi","All India"]', iu: '/images/events/independence.jpg' },
  { t: 'Constitution of India', d: 'The Constituent Assembly adopted the Constitution of India, making India a sovereign democratic republic.', da: 'January 26, 1950', y: 1950, p: 'Modern', c: 'Political', pers: '["Dr. B.R. Ambedkar","Dr. Rajendra Prasad","Jawaharlal Nehru"]', loc: '["Delhi","Constituent Assembly"]', iu: '/images/events/constitution.jpg' },
  { t: 'First General Election', d: 'India held its first general election based on universal adult suffrage, the largest democratic exercise in history.', da: 'October 25, 1951 - February 21, 1952', y: 1951, p: 'Modern', c: 'Political', pers: '["Jawaharlal Nehru","Sukumar Sen"]', loc: '["All India"]', iu: '/images/events/first-election.jpg' },
  { t: 'Indo-Pak War of 1947-48', d: 'The first war between India and Pakistan over the princely state of Jammu and Kashmir.', da: 'October 22, 1947 - January 1, 1949', y: 1947, p: 'Modern', c: 'War', pers: '["Sheikh Abdullah","Lord Mountbatten","Muhammad Ali Jinnah"]', loc: '["Kashmir","Jammu"]', iu: '/images/events/indo-pak-1947.jpg' },
  { t: 'Green Revolution', d: 'India transformed from a food-deficient nation to a self-sufficient agricultural powerhouse through high-yield crops.', da: '1960s - 1970s', y: 1960, p: 'Modern', c: 'Economic', pers: '["Dr. M.S. Swaminathan","Norman Borlaug","C. Subramaniam"]', loc: '["Punjab","Haryana","Uttar Pradesh"]', iu: '/images/events/green-revolution.jpg' },
  { t: 'Indo-Pak War of 1965', d: 'The second war between India and Pakistan over Kashmir, ending in a UN-brokered ceasefire.', da: 'August - September 1965', y: 1965, p: 'Modern', c: 'War', pers: '["Lal Bahadur Shastri","Field Marshal Ayub Khan"]', loc: '["Kashmir","Punjab","Lahore Front"]', iu: '/images/events/indo-pak-1965.jpg' },
  { t: 'Bangladesh Liberation War 1971', d: 'India intervened in East Pakistan\'s liberation war, leading to the creation of Bangladesh.', da: 'December 3-16, 1971', y: 1971, p: 'Modern', c: 'War', pers: '["Indira Gandhi","Field Marshal Sam Manekshaw","Sheikh Mujibur Rahman"]', loc: '["East Pakistan","Bangladesh","West Pakistan"]', iu: '/images/events/bangladesh-1971.jpg' },
  { t: 'Pokhran Nuclear Tests (Smiling Buddha)', d: 'India conducted its first successful nuclear test at Pokhran, becoming a nuclear power.', da: 'May 18, 1974', y: 1974, p: 'Modern', c: 'Scientific', pers: '["Indira Gandhi","Dr. Raja Ramanna","Dr. Homi Sethna"]', loc: '["Pokhran","Rajasthan"]', iu: '/images/events/pokhran-1974.jpg' },
  { t: 'Economic Reforms 1991', d: 'India introduced sweeping economic reforms opening up the economy to globalization and private enterprise.', da: 'July 24, 1991', y: 1991, p: 'Modern', c: 'Economic', pers: '["Dr. Manmohan Singh","P.V. Narasimha Rao"]', loc: '["Delhi","All India"]', iu: '/images/events/economic-reforms-1991.jpg' },
  { t: 'Kargil War', d: 'India successfully repelled Pakistani infiltrators from positions in the Kargil district of Jammu and Kashmir.', da: 'May 3 - July 26, 1999', y: 1999, p: 'Modern', c: 'War', pers: '["Atal Bihari Vajpayee","Gen. Ved Prakash Malik","Capt. Vikram Batra"]', loc: '["Kargil","Dras","Batalik"]', iu: '/images/events/kargil-war.jpg' },
  { t: 'Mars Orbiter Mission (Mangalyaan)', d: 'India became the first Asian nation to reach Mars orbit and the first nation to do so on its first attempt.', da: 'November 5, 2013 - September 24, 2014', y: 2013, p: 'Modern', c: 'Scientific', pers: '["Dr. K. Radhakrishnan","ISRO scientists"]', loc: '["Bengaluru","Sriharikota","Mars"]', iu: '/images/events/mangalyaan.jpg' },
  { t: 'COVID-19 Pandemic in India', d: 'India faced one of the world\'s largest COVID-19 outbreaks with a nationwide lockdown and massive vaccination drive.', da: 'January 30, 2020 - Present', y: 2020, p: 'Modern', c: 'Health Crisis', pers: '["Dr. V.K. Paul","ICMR","WHO"]', loc: '["All India"]', iu: '/images/events/covid19.jpg' },
];
for (const e of EVENTS_DATA) {
  insertEvent.run(generateId(), e.t, e.d, e.da, e.y, e.p, e.c, e.pers, e.loc, e.iu);
}

console.log('✅ Database seeded successfully!');
